rainbow-me/browser-extension

- package.json
- yarn.lock
> fix: checks

- lavamoat/build-webpack/policy-override.json
- lavamoat/build-webpack/policy.json
- package.json
- yarn.lock
Fixes BX-####
CI Publish jobs were failing because of some dep missconfiguration and lavamoat incompatibilities.
This PR fixes that issue
> Fix Publish Builds

- src/entries/popup/pages/swap/SwapTokenInput/TokenInput.tsx
- src/entries/popup/pages/swap/SwapTokenInput/TokenToBuyInput.tsx
- src/entries/popup/pages/swap/index.tsx
Fixes BX-####
https://github.com/rainbow-me/browser-extension/assets/6232729/c6e524ff-020f-4db4-bcfd-96dfd153f50a
> Swaps: automatically jump to output selection after input selection

- src/entries/popup/components/ExternalImage/ExternalImage.tsx
> Remove log

- src/core/state/pendingTransactions/index.ts
- src/entries/background/handlers/handleProviderRequest.ts
- src/entries/popup/pages/settings/transactions.tsx
- static/json/languages/en_US.json
Fixes BX-####
related to BX-1087
Adding a reset pending tx and noces button under transactions settings
> clear pending txs and nonces settings button

- CHANGELOG.md
- package.json
- static/manifest.json
- version bump to `v1.2.54` from rc release to fix CI/CD
> release: v1.2.54

- package.json
- yarn.lock
> bump deps for vulns

- package.json
- yarn.lock
> bump chromedriver

- src/entries/background/handlers/handleProviderRequest.ts
Fixes BX-1111
rate limit was blocking the provider request
with this pr we're now only blocking requests that need a provider request
> fix: BX-1111

- src/core/state/customRPC/index.test.ts
- src/core/state/customRPC/index.ts
- src/core/state/customRPCAssets/index.test.ts
- src/core/state/customRPCAssets/index.ts
- src/core/utils/chains.ts
- src/entries/popup/Routes.tsx
- src/entries/popup/hooks/useCustomNetwork.ts
- src/entries/popup/pages/settings/customRPC/customRPC.tsx
- src/entries/popup/pages/settings/customRPC/index.tsx
- src/entries/popup/urls.ts
Fixes BX-####
- custom rpc groups in settings
- custom rpc assets in settings
- added `useCustomNetwork` to use it in the same way we use wagmi `useNetwork` to get custom rpcs 
- added `getCustomChains` so we can call it from createWagmiClient in the same way we have wagmi's `getChains`
https://www.loom.com/share/9c849c0ad10c4897a4bb144a5fc98ecc
> feat: custom rpc assets

- static/allowlist.json
> fix bnb allowlist

- src/entries/popup/pages/home/TokenDetails/TokenDetails.tsx
Fixes BX-####
Christian just found out this flag was swapped and made the about section disappear by accident.
> Restore token details about section

- src/core/firebase/remoteConfig.ts
- src/core/providers/proxy.ts
Fixes BX-####
this sets the default value to ON
> Manage RPC proxy flag

- crowdin.yml
- static/json/languages/ar_AR.json
- static/json/languages/es_419.json
- static/json/languages/fr_FR.json
- static/json/languages/hi_IN.json
- static/json/languages/id_ID.json
- static/json/languages/ja_JP.json
- static/json/languages/ko_KR.json
- static/json/languages/pt_BR.json
- static/json/languages/ru_RU.json
- static/json/languages/th_TH.json
- static/json/languages/tr_TR.json
- static/json/languages/zh_CN.json
- Networks settings
- Developer Tools and Testnet Mode
- Malicious dApp warnings
- Wallet management right-click menus
- Clear transactions
- Points
- NFTs
- Custom Networks placeholders
> chore: i18n updates

- src/core/resources/chains/chainMetadata.ts
- src/core/utils/chains.ts
- src/design-system/styles/designTokens.ts
- src/entries/popup/components/Form/Form.tsx
- src/entries/popup/components/Form/FormInput.tsx
- src/entries/popup/pages/settings/customChain/customChain.tsx
- src/entries/popup/pages/settings/customChain/index.tsx
Fixes BX-####
- added `Form` and `FormInput` components
- when adding a custom rpc, we'll check if the url is a valid rpc endpoint getting the chainId and presenting it to the user in the chainId input of the form
- validations for custom chain was added and confirmed is working
- - when adding a custom asset, we'll check if the address is a valid address and pull the asset metadata
- validations for custom asset was added and confirmed is working
https://www.loom.com/share/95a8b1c89618435ca85749e2b936a173
> feat: custom rpc form validations

- src/core/resources/assets/userAssets.ts
- src/core/resources/nfts/nfts.ts
- src/core/utils/chains.ts
- src/entries/popup/hooks/useTransactionListForPendingTxs.ts
Fixes BX-####
updated chain names to use to fetch nfts, it was taking custom rpcs so the request was failing and no nft was appearing
> fix: NFTs fetching with custom rpc

- src/design-system/components/Button/Button.tsx
- src/entries/popup/hooks/useKeyboardAnalytics.ts
- src/entries/popup/pages/messages/AddEthereumChain/AddEthereumChainActions.tsx
- src/entries/popup/pages/messages/BottomActions/index.tsx
- src/entries/popup/pages/messages/RequestAccounts/RequestAccountsActions.tsx
- src/entries/popup/pages/messages/SendTransaction/SendTransactionActions.tsx
- src/entries/popup/pages/messages/SignMessage/SignMessageActions.tsx
- src/entries/popup/pages/messages/Tabs.tsx
- src/entries/popup/pages/messages/WatchAsset/WatchAssetActions.tsx
Fixes BX-1125
Deprecate the automatic highlight of Sign, now that we have the Cmd+Return feature
> remove accept request auto focus

- src/entries/popup/pages/home/NFTs/NFTs.tsx
I added skeleton loaders on the NFT Gallery page. They differ depending on the display mode selected.
PoW: https://recordit.co/xZ3LorqoNe
Make sure the skeleton loaders appear when `isInitialLoading` is true.
> [BX-1106] Skeleton / Loading State Nft Gallery

- src/core/providers/proxy.ts
- src/core/wagmi/createWagmiClient.ts
- src/entries/background/index.ts
- src/entries/popup/App.tsx
Fixes BX-####
passing flag from background instead of config in inpage
https://rainbowhaus.slack.com/archives/C04M9BUPQP6/p1701099096721399
> fix: update wagmi client with flag

- src/core/resources/assets/customNetworkAssets.ts
Fixes BX-####
custom network assets were appearing on testnet mode, now we'll be checking if the custom network is testnet to show it on testnet mode
> fix: filter testnet custom networks

- CHANGELOG.md
- Resolved reliability issues with malicious transaction detection upon dapp requests, and improved readability of Rainbow Canary warnings #1168
- Fixed a formatting issue with `eth_estimateGas` and `eth_gasPrice` RPC calls for dapps that could trigger an error and cause dapps to be unreliable #1163
- Added "Registered on" and "Expires in" rows in NFT Details for ENS assets #1166
- Fixed missing Flashbots toggle store migration to improve developer workflow on rehydrations #1171
- Added Testnet support for Holesky, Arbitrum Sepolia, Optimism Sepolia networks #1147
- Improved translations for Magic Menu actions, and Transaction Simulation and Decoding #1160
- Fixed dApp prompt positioning when using multiple windows and monitors #1151
- Improved keyboard navigation consistency on dApp …
> changelog: v1.2.94, v1.2.88, v1.2.78, v1.2.71

- static/json/languages/en_US.json
missing word in text that was pointed out by @benisgold in BX-740
> missing word in text

- src/entries/popup/components/Autocomplete/index.tsx
- src/entries/popup/pages/settings/customChain/index.tsx
- appended networks to the autocomplete Custom Networks list
> feat: add more pre-populated custom networks

- src/core/state/currentSettings/featureFlags.ts
- toggled `nfts_enabled`
- bumped `featureFlagsStore` version
> chore: toggle nfts_enabled feature flag

- src/core/firebase/remoteConfig.ts
- src/entries/popup/pages/home/Points/Points.tsx
- src/entries/popup/pages/home/index.tsx
- added `BX_points_enabled` to Firebase, defaulting to false
- added `points_enabled` to Firebase config
- added Firebase condition alongside local feature flag
- Points expected default empty state and local feature flag override of Firebase default
> feat: firebase remote flag for points

- src/entries/iframe/notification.tsx
<video src="https://github.com/rainbow-me/browser-extension/assets/41711440/df30ac0e-434c-4bc7-be8f-d66ec7038b25" controls="controls" style="max-width: 730px;"></video>
> [BX-1133] onClick: Dismiss network change popup 

- src/entries/popup/pages/home/Points/Points.tsx
- force feature flag check for points alongside onboarded check
- Reliability of Points feature flag
- Complete a swap, check if wallet breaks through feature flag logic and displays Points dashboard
> fix: points onboarding feature flag escape

- src/core/references/index.ts
- src/core/resources/assets/customNetworkAssets.ts
- src/core/state/customRPC/index.test.ts
- src/core/state/customRPC/index.ts
- src/core/utils/chains.ts
- src/core/wagmi/createWagmiClient.ts
- src/entries/popup/pages/settings/customChain/addAsset.tsx
- src/entries/popup/pages/settings/customChain/index.tsx
- src/entries/popup/pages/settings/rpcs.tsx
- static/json/languages/en_US.json
Fixes BX-1147
Fixes BX-1148
Fixes BX-1149
Fixes BX-1156
https://www.loom.com/share/9b997a78ab024df9b630caea6ef5cb06
after the video i commited a change to hide tokens is there are no tokens for the custom chain
> @esteban/customrpcs

- src/entries/popup/pages/messages/SendTransaction/index.tsx
- src/entries/popup/pages/send/index.tsx
- src/entries/popup/pages/swap/SwapReviewSheet/SwapReviewSheet.tsx
Fixes BX-####
showing a readable error now
> fix: extract error message from tx error

- patches/@wagmi+core+0.10.17.patch
Fixes BX-####
Removing some stuff that we don't use and while it's being removed by Webpack's treeshaking
I want to avoid any confusions at the lockfile level
> wagmi patch

- src/entries/popup/pages/settings/customChain/index.tsx
- static/json/languages/en_US.json
Fixes BX-####
Changed the name of some functions that were confusing and added an alert when the RPC endpoint it's not responding
http://recordit.co/e668FdzUM3
> Add rpc validations

- src/entries/popup/pages/settings/customChain/index.tsx
> Fix fantom chain id

- src/entries/popup/pages/settings/customChain/index.tsx
- src/entries/popup/pages/settings/networks.tsx
- src/entries/popup/pages/settings/rpcs.tsx
- static/json/languages/en_US.json
Fixes BX-####
Fixes BX-1192
Fixes BX-1191
Fixes BX-1190
http://recordit.co/KIpWvphHY1
> Fix custom networks bugs

- src/entries/popup/pages/settings/rpcs.tsx
Fixes BX-####
I think this was a bad merge. SMH
Fixes BX-1189
http://recordit.co/YBhFzgJjQ6
> fix RPC switching

- src/design-system/components/Input/Input.tsx
- src/entries/popup/pages/home/Points/PointsReferralSheet.tsx
> points support pasting whole ref link

- src/entries/popup/components/ChainBadge/ChainBadge.tsx
- src/entries/popup/pages/home/NetworkMenu.tsx
Fixes BX-1181
fixing chain badge
https://www.loom.com/share/8df2e8c6faf8464e8012a993603d1a22
> fix: custom network badge

- src/core/state/index.ts
- src/entries/popup/hooks/useRainbowChains.ts
- src/entries/popup/pages/messages/AddEthereumChain/index.tsx
- src/entries/popup/pages/settings/customChain/index.tsx
- src/entries/popup/pages/settings/networks.tsx
- src/entries/popup/pages/settings/rpcs.tsx
Fixes BX-1201
https://github.com/rainbow-me/browser-extension/assets/12115171/bb66809a-f760-4d0d-b486-d2f261a99205
> fix unsopported change to custom chain 

- src/entries/popup/pages/settings/rpcs.tsx
Fixes BX-####
- The lack of optionals was crashing the bx after removal
- We weren't navigating back after removing
http://recordit.co/oo8yHSH1SB
> Fix remove network

- src/core/state/rainbowChains/index.ts
- src/entries/background/handlers/handleProviderRequest.ts
- src/entries/iframe/index.ts
- src/entries/iframe/notification.tsx
- src/entries/inpage/index.ts
- src/entries/popup/components/ChainBadge/ChainBadge.tsx
Fixes BX-1202
https://github.com/rainbow-me/browser-extension/assets/12115171/edd5a80a-eead-49e3-8900-ce6ea2ccfef2
> fix: custom chain inpage notification

- src/core/utils/chains.ts
- src/entries/popup/components/AppConnection/AppConnectionWalletItem/AppConnectionWalletItem.tsx
- src/entries/popup/hooks/useSearchCurrencyLists.ts
- src/entries/popup/pages/home/TokenDetails/TokenDetails.tsx
- src/entries/popup/pages/messages/AccountSigningWith.tsx
- src/entries/popup/pages/messages/SendTransaction/SendTransactionsInfo.tsx
Fixes BX-1205
fixing BX-1205 again and including all of the places we use chain name
> fix: chain names

- src/core/resources/assets/customNetworkAssets.ts
- src/core/utils/chains.ts
- src/entries/popup/components/Draggable/index.tsx
- src/entries/popup/pages/settings/customChain/addAsset.tsx
- src/entries/popup/pages/settings/customChain/index.tsx
- src/entries/popup/pages/settings/networks.tsx
- src/entries/popup/pages/settings/rpcs.tsx
Fixes BX-####
fixing
- when adding tokens or removing the ui is updating instantly according to the store slice
- reordering networks functionality broke 
- reordering networks had a jump happening
> networks tweaks

- src/entries/popup/pages/settings/customChain/index.tsx
Fixes BX-####
We don't need to expose this field at all.
https://recordit.co/18tFU4Ba7p
> hide chain id

- src/entries/popup/pages/home/Points/PointsOnboardingSheet.tsx
> Fix points error handling

- src/core/references/index.ts
- src/core/resources/assets/userTestnetNativeAsset.ts
- src/entries/popup/hooks/useNativeAsset.ts
Fixes BX-1220
for empty wallets with no assets we're not fetching the native assets so this bug was happening
with this pr i'm introducing mock assets to have the native assets with prices coming from backend but balance being 0 so the user will see the tx fee correctly
https://www.loom.com/share/85086669138243bdbcbcb1ba0415e8a3
> fix: BX-1220

- src/entries/popup/pages/home/Points/PointsDashboard.tsx
> points fix leaderboard bottom padding

- src/core/keychain/RainbowSigner.ts
Fixes BX-1221
adding `@ethereumjs/common` Common data signing txs to fix the invalid sender error in some custom chains
sending txs
https://www.loom.com/share/f6c7df62dbe045dd95bb6f256e3b216d
> fix: BX-1221

- src/entries/popup/pages/settings/customChain/index.tsx
Fixes BX-####
https://github.com/rainbow-me/browser-extension/assets/6232729/1c380972-ec1a-4249-b8ae-cea8f60e32e9
> custom networks skip validation of autocompleted networks

- src/entries/popup/pages/messages/Simulation.tsx
Fixes BX-1217
Fixes #1269
before / after
> fix simulation "unlimited" amount

- package.json
- yarn.lock
> bump follow-redirects

- package.json
- yarn.lock
Fixes BX-1222
bumping lib, details in ticket
> bump eth-sig-util

- src/core/resources/_selectors/assets.ts
- src/entries/popup/pages/home/Tokens.tsx
- src/entries/popup/pages/settings/customChain/index.tsx
Fixes BX-1246
Fixes BX-1247
Fixing ticket
- adding chainId validation
- getting chainId from network from rpc
- filtering custom networks correctly
https://www.loom.com/share/4da9941cb2774d4e82f171dcb84f0f37
> fix: validate chainId for known networks

- src/core/state/navRestoration/index.ts
Fixes BX-####
Fixes https://rainbow-me.sentry.io/issues/4740718765/?project=4504012577112064&query=&referrer=issue-stream&statsPeriod=7d&stream_index=0&utc=true
Fixes https://rainbow-me.sentry.io/issues/4745906668/?project=4504012577112064&query=&referrer=issue-stream&statsPeriod=7d&stream_index=1&utc=true
> add undefined check for top 2 sentry erros

- src/entries/background/handlers/handleProviderRequest.ts
- src/entries/iframe/notification.tsx
- src/entries/inpage/index.ts
- static/json/languages/en_US.json
Fixes BX-1231
implementing ticket
https://www.loom.com/share/e2027f611c6546ea99f63dd70146a9b9
EDIT
@brunobar79 pointed out the case where you are adding a rpc that you want like flashbots, in which case we shouldn't block and set as active instead
this pr is not:
- adding new custom rpc and setting it as active if the rpc url is not present
- setting new custom rpc as active if the rpc url is present but is not currently active
https://www.loom.com/share/df682b11e3374bbca9fc4616c6b55440
> block add chain duplicates

- package.json
- yarn.lock
Fixes BX-####
Avax support on the sdk
> Bump Swaps SDK

- audit-ci.jsonc
Fixes BX-####
- allowlisted `GHSA-c24v-8rfc-w8vw`
> fix: ci, allowlist vitest vulnerability

- src/entries/popup/components/AddressDisplay.tsx
- src/entries/popup/pages/messages/SendTransaction/SendTransactionsInfo.tsx
- static/json/languages/en_US.json
Fixes: BX-1280
POW:
<video src="https://github.com/rainbow-me/browser-extension/assets/41711440/e97f21ac-121d-4209-b06c-41e2bdd63b32" />
Few more examples with Daniels fixes in:
> Add Etherscan link to txn sim > details > contract

- src/core/utils/chains.ts
- src/entries/popup/pages/settings/customChain/index.tsx
Fixes BX-####
- migrated to rari chain mainnet in autopulated list
- added rari chain to simplehash support list
- added rari mainnet chain id
> chore: add rari chain support

- src/core/references/gasUnits.ts
Fixes BX-1301
3_500_000 is too low, most of the swaps go with 4_500_000 to 5_000_000
> bump default gas limit for arb swap

- lavamoat/build-webpack/policy.json
Fixes BX-####
- generated webpack policy updates to go along with #1349
> chore: policy updates

- .env.d.ts
- src/core/references/index.ts
- src/core/types/chains.ts
- src/core/types/nfts.ts
- src/core/utils/chains.ts
- src/core/utils/faucets.ts
- src/core/utils/nfts.ts
- src/core/utils/userChains.ts
- src/entries/iframe/notification.tsx
- src/entries/popup/components/ChainBadge/ChainBadge.tsx
Fixes BX-####
- removed references to `zoraTestnet` (Zora Goerli Testnet)
- removed `ZORA_GOERLI_RPC`
> chore: deprecate zora goerli

- lavamoat/build-webpack/policy.json
- src/core/utils/chains.ts
- src/entries/popup/pages/settings/customChain/index.tsx
Fixes BX-####
- added `blast` network to auto-populated list
- bumped outstanding policy changes
> feat: blast network support

- src/core/resources/assets/customNetworkAssets.ts
- src/core/resources/assets/userAssets.ts
- src/core/types/assets.ts
- src/core/utils/assets.ts
- src/entries/popup/pages/home/Tokens.tsx
Fixes BX-1337
fixed chain ids and unique ids of native asset that was causing this issue when getting assets from backend originating the issue
> fix: blast custom rpc

- src/core/resources/transactions/transaction.ts
- src/design-system/components/BottomSheet/BottomSheet.tsx
- src/entries/popup/pages/home/Activity/ActivityDetails.tsx
- src/entries/popup/pages/home/Activity/ActivityPill.tsx
> Activity details fixes

- package.json
- src/core/transports/providerRequestTransport.ts
- src/entries/popup/pages/messages/AddEthereumChain/index.tsx
- src/entries/popup/pages/messages/WatchAsset/index.tsx
- yarn.lock
Fixes BX-1326
https://github.com/rainbow-me/provider/pull/4
https://www.loom.com/share/80cc88c3cdc94f9d8c66348286d184eb
> fix: BX-1326

- lavamoat/build-webpack/policy.json
- package.json
- src/entries/popup/pages/home/Points/WeeklyPointsOverview.tsx
- yarn.lock
Fixes BX-1343
needed to * 1000 the date. was returning the value in miliseconds, not seconds. the actual returned date was Jan of 1970 lol
> Fix date on points terminal

- src/entries/popup/components/AppConnection/AppConnectionWatcher.tsx
Fixes BX-1357
updating logic to match ticket
https://www.loom.com/share/0c0be25e01164468bb849db812b120f6
> fix: BX-1357

- package.json
- src/core/resources/search/tokenSearch.ts
- src/entries/popup/components/SwitchMenu/SwitchNetworkMenu.tsx
- src/entries/popup/hooks/swap/useSwapAssets.ts
- src/entries/popup/hooks/useSearchCurrencyLists.ts
- yarn.lock
Fixes BX-####
adding bridging to blast
> add: blast bridge

- src/core/resources/assets/common.ts
- src/core/resources/assets/userAssets.ts
- src/core/utils/assets.ts
Fixes BX-1360
Fixes BX-1285
removing token filtering for assets
https://rainbowhaus.slack.com/archives/C04M9BUPQP6/p1710963035267049
> remove token filter

- e2e/parallel/shortcuts-settings.test.ts
- src/entries/popup/pages/settings/settings.tsx
- static/json/languages/en_US.json
Fixes BX-####
- reordered settings list to include higher priority items in the first bucket
- moved sounds toggle to bottom of the list to raise theme priority
- fixed old "beta feedback" request
> reorder settings menus

- src/core/keychain/KeychainManager.test.ts
- src/core/keychain/KeychainManager.ts
- src/core/keychain/keychainTypes/hardwareWalletKeychain.ts
- src/core/keychain/keychainTypes/hdKeychain.ts
- src/core/keychain/keychainTypes/keyPairKeychain.ts
- src/core/keychain/keychainTypes/readOnlyKeychain.ts
Fixes BX-####
remove some type castings
> improve type safety of keychain manager

- src/entries/popup/pages/walletSwitcher/chooseWalletGroup.tsx
> fix spacing in choose wallet group

- lavamoat/build-webpack/policy.json
- package.json
- src/core/raps/actions/swap.ts
- src/core/raps/actions/unlock.test.ts
- src/core/raps/unlockAndSwap.ts
- src/core/raps/utils.ts
- yarn.lock
> bump swaps sdk (inc. Blast & Zora support)

- src/design-system/styles/core.css.ts
- src/entries/popup/pages/walletReady/index.tsx
> onboarding fix position of "pin extension" in arc browser

- src/core/firebase/remoteConfig.ts
We are adding a new feature flag `defi_positions_enabled` to the project to enable incremental development on the feature set.
> [BX-1372] chore: add defi positions flag

- .env.d.ts
- src/core/references/index.ts
- src/core/types/chains.ts
- src/core/types/nfts.ts
- src/core/utils/chains.ts
- src/core/utils/faucets.ts
- src/core/utils/nfts.ts
- src/core/utils/userChains.ts
- src/entries/iframe/notification.tsx
- src/entries/popup/components/ChainBadge/ChainBadge.tsx
Fixes BX-####
- created `chainPolygonAmoy` chain
> add polygon amoy testnet

- src/entries/popup/components/ExternalImage/ExternalImage.tsx
Fixes BX-1380
adding imgPromise to useImage https://www.npmjs.com/package/react-image to remove the error described in ticket
> fix: BX-1380

- package.json
- yarn.lock
Fixes BX-####
bumping @rainbow-me/swaps to latest version
> bump @rainbow-me/swaps

- static/allowlist.json
Fixes BX-####
- it appears that `rpc.zora.co` was deprecated in favor of `rpc.zora.energy`
Note: we also need migrations here for users that added already added the `rpc.zora.energy` custom rpc
> chore: amend zora rpc

- src/core/state/rainbowChains/index.ts
Fixes BX-####
this migration was working for this specific case https://github.com/rainbow-me/browser-extension/pull/1467 but was removing all other custom rpcs 💀
> fix: migration removeCustomRPC

- CHANGELOG.md
- Fixed an issue with balance estimation during Sends on Polygon and BSC #1472
- Now showing the right transaction explorer in the right-click menu on Activity #1419
- Fixed an issue that hid failed transactions from the Activity list #1419
- Resolved transaction display settlement issues after performing a Swap, to prevent incorrect transaction types from being displayed #1419
- Improved currency display values in Activity Details for each transaction #1419
- Resolved cell highlight rounding issues on the Settings menu when navigating with your keyboard #1464
- Resolved missing asset icons in the Activity list #1468
- Amended Zora RPC url to favor new domain #1466
- Added a migration to remove Custom RPCs added by Zora.co #1467 #1475
- Fixed test retries by moving retry logic to the …
> changelog v1.4.55, v1.4.50, v1.4.48

- src/entries/popup/hooks/useInfiniteTransactionList.ts
Fixes BX-####
before 
https://github.com/rainbow-me/browser-extension/assets/12115171/1bb9288f-4f3b-4acc-a5ce-e3bac6fca235
now 
https://github.com/rainbow-me/browser-extension/assets/12115171/5eefe44c-3e24-44f4-8cd5-d0ef0dc89fbe
> fix: filter txs by enabled user chains

- lavamoat/build-webpack/policy.json
- package.json
- yarn.lock
> [BX-1415] chore: bump tar via resolutions

- src/entries/background/handlers/handleProviderRequest.ts
Fixes BX-####
isSupportedChain was only checking default chains so at the moment of switch chain, if the new chain was a custom chain you wouldn't be able to connect
before 
https://github.com/rainbow-me/browser-extension/assets/12115171/c65e5a2e-a217-4c14-9d93-6075074dcd74
now
https://github.com/rainbow-me/browser-extension/assets/12115171/85dc145c-10b4-4650-a0fe-892a98122d50
> fix: handle provider request isSupportedChain

- lavamoat/build-webpack/policy.json
- package.json
- yarn.lock
> chore: bump protobufjs

- src/entries/popup/pages/messages/Simulation.tsx
Added price fetching in tx simulation rows to allow us to show native currency values
Ensure native currency values appear within tx simulation
> [BX-1410] feat: add native currency values to tx simulation

- package.json
- yarn.lock
> chore: bump phin

- lavamoat/build-webpack/policy.json
- src/core/graphql/queries/metadata.graphql
- src/entries/popup/pages/messages/SignMessage/SignMessageInfo.tsx
- src/entries/popup/pages/messages/useSimulateTransaction.tsx
Fixes BX-1320
details in ticket
passing currency in tx simultaion request
> pass currency in tx simulation

- lavamoat/build-webpack/policy.json
- package.json
- yarn.lock
Fixes BX-####
- bump `@solana/web3.js` for CI audit
- is she broke
> bump @solana/web3.js resolution

- src/core/state/currentSettings/currentTheme.ts
- src/design-system/styles/initThemingCritical.ts
- src/design-system/styles/initThemingLocal.ts
- src/entries/popup/index.html
- src/entries/popup/index.ts
- static/theming.js
- static/themingBody.js
Fixes BX-####
removing flash white screen on startup
with this pr we'll be initializing theme from index.html
before we were doing this from `initThemingCritical` and `initThemingBody` causing the flash since those take a fraction of a second after dom is loaded to be initialized
https://www.loom.com/share/f0e221cff41b4f188cc00462cad61fd2
> remove white flash screen on startup

- src/analytics/index.ts
Fixes BX-####
- temporarily altered flush behavior to mitigate event drops
> fix: patch rudderstack flush behavior

- src/entries/popup/components/CommandK/useCommands.tsx
- src/entries/popup/hooks/useInfiniteTransactionList.ts
Fixes BX-####
- fixed a ci/linting issue introduced on #1526 related to command k actions
- there is apparently a race condition for a few seconds/mins with the merge queue when pushing a new commit and ci checks from a previous commit finishing up, where untested commits can get merged
> fix: open profile command for contacts cmdk

- package.json
- src/entries/popup/pages/messages/RequestAccounts/index.tsx
- yarn.lock
Fixes BX-####
now triggering a connection request when switching network if there's no active session
more details and video here https://rainbowhaus.slack.com/archives/C044WE28BTK/p1714773513016329
> trigger connection when no active session

- CHANGELOG.md
- You can now search for a Token Contract Address in Swaps to more quickly find a token #1561
- Resolved gas estimation issues for Blast and Degen chain #1559 #1566
- Fixed the `To` field in Activity Details for a transaction to better reflect a transaction recipient #1567
- Resolved `NaN` balances displayed on the Tokens tab while reloading balances #1562
- Fixed text overflows for alternative languages on the Tip Banner on the Tokens tab #1563
- Consolidated chains info to prepare for new Chains Metadata endpoint #1554
- You can now search for Token Contract Addresses in the Magic Menu with Cmd+K to easily find and get an asset #1547
- Resolved accuracy of Ethereum Sepolia and additional testnet gas estimates #1546
- Fixed a crash for some browsers that attempted to translate the …
> changelog: v1.4.111, v1.4.122

- src/core/types/transactions.ts
- src/core/utils/transactions.ts
Fixes BX-1498
now displaying approval to correctly
now using meta.type for this method since type is deprecated
> fix: approve tx to

- .github/workflows/publish-internal.yml
- src/entries/popup/hooks/swap/useSwapQuote.ts
Fixes BX-####
more info here https://github.com/rainbow-me/browser-extension-action
> feat: browser extension action

- lavamoat/build-webpack/policy.json
- package.json
- yarn.lock
- bumping resolution to fix CI
> add ws resolution

- .github/workflows/publish-internal.yml
Fixes BX-####
updating key from https://github.com/rainbow-me/browser-extension/pull/1577
> github action update

- .github/workflows/publish-internal.yml
- src/entries/popup/hooks/swap/useSwapQuote.ts
> internal builds

- lavamoat/build-webpack/policy.json
- package.json
- static/manifest.json
- Resolves version mismatch after generating an internal build on a different branch
> Version Bump (Internal) - v1.4.131

- src/core/references/chains.ts
- src/core/state/rainbowChains/index.ts
- src/core/state/rainbowChains/utils.ts
- src/entries/popup/pages/settings/rpcs.tsx
Fixes BX-####
added a missing migration missing here https://github.com/rainbow-me/browser-extension/pull/1564
to update rpc urls
> Missing migration for chains

- package.json
- static/manifest.json
Fixes BX-####
- version bump to 1.5.0 to unblock future internal releases
> v1.5.0 version bump

- src/entries/popup/pages/home/Points/ClaimSheet.tsx
Fixes BX-1534
Displaying OP as first option if bridge disabled
Ensure network order changes when bridging is disabled in claim flow
> fix: position OP as top claim item

- src/entries/popup/pages/home/Points/OldPointsDashboard.tsx
Fixes BX-1533
We have updated our skeleton logic to prevent rendering the old points screen content until after firebase config is ready. 
https://www.loom.com/share/d95216b14e8442ca8825ae024e4d8ed7
Ensure that old points do not render (without skeletons) while the firebase config is loading.
> fix: present skeleton while loading config on points screen

- src/core/raps/actions/claimBridge.ts
> take into account l1 op  gas fee for claimBridge

- src/entries/popup/pages/home/Points/PointsDashboard.tsx
- https://rainbowhaus.slack.com/archives/C044WE28BTK/p1719335216986159
- using `handleSignificantDecimalsWithThreshold` to round number
> fix stimmy rounding

- src/entries/inpage/index.ts
Fixes BX-1540
fixing ticket, seems like we had a something not configured well in inpage when coinbase wallet is present, not really sure why but this fixes the issue
maybe was this line https://github.com/rainbow-me/browser-extension/pull/1599/files#diff-d13d2b4eaccf47cdf4ab7013649e5884d9a92832fe986e41e5dcad32f9c1e031L149 trying to set a freezed value, but is weird that is not an issue for most of users
> fix: BX-1540

- lavamoat/build-webpack/policy.json
- src/entries/popup/pages/home/Points/ClaimOverview.tsx
- src/entries/popup/pages/home/Points/PointsDashboard.tsx
Fixes BX-1541
- couple other places in the flow where the decimals were not rounded at 6 spots
BEFORE:
AFTER:
> Fix stimmy rounding pt 2

- src/core/raps/actions/swap.ts
Fixes BX-1553
we were missing correct call params for unwrap so this estimation never worked
> fix: unwrap gas limit

- package.json
- yarn.lock
Fixes BX-####
- upgraded to `10.12.3` to see if it resolves Sentry errors related to `chrome.storage` calls in Incognito mode upon initialization
> chore: firebase upgrade

- lavamoat/build-webpack/policy.json
- src/core/graphql/__generated__/metadata.ts
- src/core/graphql/queries/metadata.graphql
- src/entries/popup/pages/messages/useSimulateTransaction.tsx
Fixes BX-1513
adding simulateTransactionsWithoutGas to be used with useSimulateTransaction in dapp tx request
> fix: BX-1513

- src/entries/popup/components/DropdownInputWrapper/DropdownInputWrapper.tsx
- src/entries/popup/hooks/useSearchCurrencyLists.ts
- src/entries/popup/pages/swap/SwapTokenInput/TokenDropdown/TokenToBuyDropdown.tsx
- src/entries/popup/pages/swap/SwapTokenInput/TokenDropdown/TokenToBuySection.tsx
- src/entries/popup/pages/swap/SwapTokenInput/TokenDropdown/TokenToSellDropdown.tsx
Fixes BX-1388
- swap lists are now using tanstack virtualized correctly
https://www.loom.com/share/795c5248637f4c1ebfd902a12d9b2ada
> swap lists virtualization

- lavamoat/build-webpack/policy.json
- src/entries/popup/pages/swap/SwapSettings/SwapSettings.tsx
- src/entries/popup/pages/swap/index.tsx
Fixes BX-1547
not showing routes on bridge flow as ticket describes
> fix: dont show bridge route

- src/entries/popup/hooks/swap/useSwapInputs.ts
Fixes BX-1548
adding 10% buffer to improve this case
> fix: BX-1548

- e2e/serial/send/3_customNetworks.test.ts
- src/entries/popup/hooks/swap/useSwapQuote.ts
Fixes BX-####
using `placeholderData` to maintain the previous request `quote` so is not undefined while updating it
> fix: BX-1567

- src/entries/popup/components/DropdownInputWrapper/DropdownInputWrapper.tsx
Fixes BX-####
i couldn't scroll in send tokens list
> fix: send tokens scroll

- e2e/parallel/commandKFlow.test.ts
- e2e/parallel/shortcuts-home.test.ts
- src/entries/popup/components/CommandK/useCommands.tsx
- src/entries/popup/components/CommandK/utils.ts
- static/json/languages/en_US.json
Fixes BX-1571
- Added Bridge shortcut in Cmd+K
- Bumped the rank for Bridge and Swap so they appear before NFTs in Cmd+K
- Bridge shortcut should work in Cmd+K
- Ranking for Swap and Bridge shortcut should appear first, used this wallet for testing `0xbE957A475844c127DDD207B4ff1F63900FD13E57`
> feat: bridge in Cmd+K

- src/core/raps/actions/claimBridge.ts
- src/core/raps/actions/crosschainSwap.ts
- src/core/references/index.ts
> chore: set referrer for claims

- lavamoat/build-webpack/policy.json
- src/core/providers/proxy.ts
- src/entries/popup/handlers/wallet.ts
Fixes BX-1589
Details and repro steps in ticket
The issue was that we weren't proxying the custom rpc since it was a default rainbow chain id, now we'll proxy all chain rpcs that aren't rainbow's rpcs
> fix: proxy

- src/entries/popup/pages/home/Points/ClaimOverview.tsx
Fixes BX-1607
- resolved i18n key issue for claim sheet
> fix: claim eth value i18n issue

- lavamoat/build-webpack/policy.json
- package.json
- src/core/types/assets.ts
- src/core/utils/swaps.ts
- src/entries/popup/hooks/swap/useSwapNativeAmounts.tsx
- src/entries/popup/pages/swap/SwapTokenInput/TokenInfo/TokenToBuyInfo.tsx
- yarn.lock
Fixes BX-####
- Bump sdk with correct types for wrap / unwrap quotes
- Fix wrapping / unwrapping
-  Hide price impact for wrapping / unwrapping
https://github.com/user-attachments/assets/15a050ed-327c-4efd-831c-2fa12f7757e7
Wrapping / Unwrapping
> Fix Wrap / Unwrap

- static/json/languages/ar_AR.json
- static/json/languages/es_419.json
- static/json/languages/fr_FR.json
- static/json/languages/hi_IN.json
- static/json/languages/id_ID.json
- static/json/languages/ja_JP.json
- static/json/languages/ko_KR.json
- static/json/languages/pt_BR.json
- static/json/languages/ru_RU.json
- static/json/languages/th_TH.json
- static/json/languages/tr_TR.json
- static/json/languages/zh_CN.json
Fixes BX-####
- added degen mode translations
> chore: degen mode translations

- lavamoat/build-webpack/policy.json
- package.json
- yarn.lock
Fixes BX-1614
Advisory title: Regular Expression Denial of Service (ReDoS) in micromatch
Advisory URL: https://github.com/advisories/GHSA-952p-6rrq-rcjv
> [CI] audit - micromatch resolution

- src/entries/popup/pages/home/Points/PointsDashboard.tsx
Fixes BX-1568
- adopted `qualified_referees` to match the app
> points: favor qualified referees over total referees

- src/core/resources/search/tokenDiscovery.ts
- src/core/resources/search/tokenSearch.ts
- src/entries/popup/components/CommandK/useSearchableTokens.ts
- src/entries/popup/hooks/useFavoriteAssets.ts
- src/entries/popup/hooks/useSearchCurrencyLists.ts
Fixes BX-1640 & BX-1670
- fix bug where favorite tokens were not in the favorites section
- update popular in rainbow section when searching
- favoriting a token in a section above the "favorited" like in the "popular in rainbow" section, should not move the token row down to "favorited" but just toggle the star
https://github.com/user-attachments/assets/6a48c54f-0cd9-47ce-9cb4-74eb9787309c
> swap search fixes

- src/entries/popup/pages/home/Activity/ActivityDetails.tsx
Fixes BX-####
yay or nay? I like just Hash
> rename TxHash to just Hash

- lavamoat/build-webpack/policy.json
- src/core/raps/actions/swap.ts
- src/core/raps/unlockAndCrosschainSwap.ts
- src/core/raps/unlockAndSwap.ts
Fixes BX-1679
- I bumped our swapsSDK last week on the BX but didn't fully migrate it. This was causing some native wraps to fail.
> remaining of swaps sdk migrations, fix wrap/unwrap

- audit-ci.jsonc
- lavamoat/build-webpack/policy.json
Fixes BX-1684
- added the advisory to our allowlist
- no available version that solves conflict
- github hasn't had a push in 5 years
> useragent audit vuln

- e2e/serial/send/4_nft-sendFlow.test.ts
- The NFT we were searching for was no long being indexed or showing up. didn't look deeply into why but no other features seem impacted so I am assuming it's an issue with the NFT itself.
- Changed to a POAP
- Removed dead FF specific code
- Removed un-needed test adding a secondary wallet and switching wallets. This is covered in send test 1 already.
> Fix NFT send test

- src/entries/popup/handlers/ledger.ts
- src/entries/popup/hooks/approveAppRequest/useApproveAppRequestValidations.ts
- src/entries/popup/pages/hw/walletList/AccountIndex.tsx
- src/entries/popup/pages/hw/walletList/index.tsx
- src/entries/popup/pages/messages/SendTransaction/SendTransactionActions.tsx
- src/entries/popup/pages/messages/SendTransaction/index.tsx
- src/entries/popup/pages/messages/SignMessage/SignMessageActions.tsx
- src/entries/popup/pages/messages/SignMessage/index.tsx
Fixes BX-1686
Fixes BX-1661
Fixes BX-1660
Fixes BX-1646
- [Ensured bridging via common dapps works while using a Trezor Wallet [BX-1686]](https://www.loom.com/share/ac48577fe3bf4be787dfcc126622fd82)
- [We are now preventing an infinite spinner when a user attempts to import multiple indices from a HW device and at least one of the accounts has already been imported. [BX-1661]](https://www.loom.com/share/d45960078beb415e94d8bbe6b7c7d955)
- We corrected a small UI issue reported on the add wallets screen [BX-1660]
- [We are now determining whether a user is signing a dapp request (sign + send) with a hw device prior to the user interacting with the sign CTA](https://www.loom.com/share/9967282a2a194c0fb0680661b60ff115). [We are now also appropriately handling the disconnected ledger flow. …
> HW Clean Up

- .github/workflows/publish-internal.yml
- .github/workflows/publish-prod-chrome.yml
- .github/workflows/publish-prod-firefox.yml
Reverts rainbow-me/browser-extension#1786
We actually need this to commit the release changes on the job
> Revert "Remove unncessary token from publish jobs"

- package.json
- yarn.lock
Fixes BX-####
- pinned `nanoid@3.3.8` to resolve https://github.com/advisories/GHSA-mwcw-c2x4-8c55
> fix: CVE-2024-55565

- .github/workflows/build.yml
- Added missing policy files
- Added additional yarn setup step to fix bad builds between jobs on different runners
None
Build job should be green
> fix: policy builds artifact conflict

- .github/workflows/publish-internal.yml
- .github/workflows/publish-prod-chrome.yml
- .github/workflows/publish-prod-edge.yml
- .github/workflows/publish-prod-firefox.yml
- package.json
Fixes BX-####
Awaiting BPP changes to be merged
- publish to edge store
- re-enable firefox upload, added source upload zip
> edge, firefox automatic submission

- .github/workflows/publish-prod-firefox.yml
Fixes BX-####
- fixed the publish ci input key for firefox source files
> fix: source input value for bpp

- .github/workflows/publish-prod-firefox.yml
Fixes BX-####
Uploading source submission as an artifact
> fix: firefox ci source artifact upload

- src/entries/popup/pages/walletSwitcher/addWallet.tsx
flag was wrong. now it works on this flow. POW:
<video src="https://github.com/user-attachments/assets/39e39224-a135-489c-b44f-565786923e0e"></video>
> flip hw flag

- .github/workflows/publish-prod-firefox.yml
Fixes BX-####
- Fixed re-zip behavior for Firefox build artifact
> fix: firefox build artifact re-zip

- .github/workflows/build.yml
- e2e/serial/dappInteractions/1_appInteractionsFlow.test.ts
seems like were having some memory issues with CI. swiching to beefy-runner-bx for dapp tests fixed a failure we were having.
> tesing beefy runner for dapp stuff

- lavamoat/build-webpack/policy.json
- package.json
- static/manifest.json
> manual bump for resubmission

- src/core/raps/actions/crosschainSwap.ts
- src/core/raps/actions/swap.ts
Fixes BX-####
Added extra checks to make sure we're not sending swaps through the wrong flow
> Add extra checks for swap types

- package.json
- src/entries/popup/hooks/swap/useSwapQuote.ts
- yarn.lock
Fixes BX-1752
Although we patched the original issue, these changes will fix the underlying problem going forward.
[Stale Req Cancellation PoW - Watch Video](https://www.loom.com/share/5cce9a3063e74699a635c8d9aa69cf68)
Let's ensure past quotes are cancelled appropriately.
> fix: consume signal in order to cancel stale reqs in useSwapQuote

- package.json
- yarn.lock
> chore: update swaps sdk to 0.32.0

- src/analytics/event.ts
- src/entries/popup/components/TransactionFee/CustomGasSheet.tsx
- src/entries/popup/pages/messages/SendTransaction/index.tsx
- src/entries/popup/pages/messages/SignMessage/index.tsx
- src/entries/popup/pages/send/index.tsx
- src/entries/popup/pages/swap/onSwap.tsx
Fixes BX-1707, BX-1706
This PR adds comprehensive hardware wallet tracking capabilities across our transaction analytics events, including vendor information (Ledger/Trezor) alongside the existing hardware wallet flags.
- Updated analytics event types to include a consistent `hardwareWallet` object structure:
```typescript
hardwareWallet: {
isHardwareWallet: boolean;
vendor?: 'Ledger' | 'Trezor' | undefined;
}
```
- Implemented this new structure across multiple transaction events:
- Bridge/Swap submissions
- Send transactions (both for assets and NFTs)
- dApp transaction submissions
- Sign message interactions
- Standardized the hardware wallet tracking format across all transaction-related events
- Added a new `dappTransactionSubmitted` event to track dApp interactions with hardware …
> [Analytics] Hardware Wallet Vendor Tracking

- lavamoat/build-webpack/policy.json
- package.json
- yarn.lock
Fixes BX-1774
- Fixes a couple CI issues that were hanging up our audit. more details in Linear ticket.
> [CI] audit ci fixes - bump a few packages

- package.json
- src/core/raps/actions/swap.ts
- src/core/raps/unlockAndSwap.ts
- src/core/raps/utils.ts
- yarn.lock
bumped swaps, deferring to a now variable set of swap target addresses
Typical swap flow with the addition of swaps including low liquidity RSTs (small buys after launch, then dumping into low liquidity pool), and RST for RST.
> Use Target Address From Swap

- e2e/serial/send/3_customNetworks.test.ts
- lavamoat/build-webpack/policy.json
- package.json
- src/entries/popup/pages/settings/customChain/index.tsx
- yarn.lock
Every few days one of the RPCs were putting in quits responding for a while and it breaks e2e for several hours. added a second RPC as a fallback
> fix flaky tests

- lavamoat/build-webpack/policy.json
- package.json
- yarn.lock
BX-1777
More details on the issue on linear!
> Ci Audit fix

- lavamoat/build-webpack/policy.json
- package.json
- yarn.lock
Fixes BX-1778
more info in linear ticket!
> audit fix - bump resolution minor version

- .github/workflows/publish-internal.yml
- .github/workflows/publish-prod-chrome.yml
- .github/workflows/publish-prod-edge.yml
- .github/workflows/publish-prod-firefox.yml
Fixes BX-####
- upgraded to bpp 3.8.0 to fix Node 20 warnings, firefox source key mismatch
> chore: bpp 3.8.0 upgrade

- audit-ci.jsonc
- lavamoat/build-webpack/policy.json
- package.json
- yarn.lock
Fixes BX-1781
More details on linear.
> Two audit fixes

- src/entries/popup/hooks/useUserChains.ts
Fixes #1872
Changes some filtering logic to no longer remove supported testnets when looking for enabled status. We only store mainnet chainIds (or any custom added network) in the enabledChainIds Set, so this was mistakenly removing supported testnets since those aren't in that Set.
test that proper chains show in the network switcher throughout the extension
> Fix useUserChains filtration to account for mainnetId for disabling supported testnets

- src/core/utils/formatDate.ts
- static/json/languages/en_US.json
Fixes BX-1744
- added logic to handle hour
- added label
> Add hour logic and change label

- lavamoat/build-webpack/policy.json
- package.json
- static/manifest.json
> Rc branch - v1.5.108
