rainbow-me/browser-extension

package.json
static/manifest.json

- bump `1.2.25` to `1.2.26` to correct version mismatch caused by simultaneous merging and internal build publish

chore: bump version

---

src/core/resources/search/tokenSearch.ts
src/entries/popup/hooks/useSearchCurrencyLists.ts

- Speeds up the swap output search by filtering out unverified results if the search query length is less than 3 characters

Hide unverified token search results for short queries

---

src/core/keychain/index.ts
src/core/utils/ethereum.test.ts
src/core/utils/ethereum.ts
src/core/utils/signMessages.tsx

Fixes BX-1051
Added sanitize function to filter out fields that doesn't match the types in the message that's being signed to prevent phishing attempts. With this fix what you see is what you sign.
Unit tests were added

add sanitizeTypeData function with tests

---

src/entries/popup/handlers/ledger.ts
src/entries/popup/handlers/trezor.ts

Fixes BX-1043
Don't blow up if the message is already a hex string
Personal Sign with trezor & ledger devices

handle hex in personal signing for HW

---

src/core/state/appConnectionWalletSwitcher/appConnectionSwitcher.ts
src/entries/popup/components/AppConnection/AppConnectionWatcher.tsx
src/entries/popup/hooks/useAppSession.ts

Fixes BX-1042
check ticket for more details
updated logic
banner sheet will appear the first time you switch account and you haven’t checked the “not show me this again” checkbox, after that the banner nudge will appear for all wallets except for the one that’s connected
https://github.com/rainbow-me/browser-extension/assets/12115171/d0acca47-f991-4b11-8496-d9b79873b218

improve wallet switcher banner logic

---

src/core/providers/RainbowInjectedProvider.ts

Fixes BX-1088
now:
when our default rnbw provider toggle is off and the user has metamask, we're relaying requests to mm provider
this was probably causing the issue, users had the tooggle off, eip6963 was picking rainbow correctly but we were relaying requests to mm
with this pr:
when our default rnbw provider toggle is off and the user has metamask we're still using rainbow provider if the dapp pick the rainbow provider 
this won't affect the window.ethereum override when the rnbw by default tooggle is on since that logic is happening on `inpage`

fix: do not default to mm provider when toggle is off

---

src/analytics/flushQueuedEvents.ts
src/analytics/queueEvent.ts
src/core/keychain/KeychainManager.ts
src/core/react-query/queryClient.ts
src/core/state/internal/persistStorage.ts
src/core/state/internal/syncStores.ts
src/core/storage/index.ts
src/core/utils/settings.ts
src/core/wagmi/createTestWagmiClient.ts
src/core/wagmi/createWagmiClient.ts
src/entries/background/handlers/handleDisconnect.ts
src/entries/background/handlers/handleProviderRequest.ts
src/entries/popup/components/IdleTimer/IdleTimer.tsx
src/entries/popup/components/ImportWallet/ImportWalletSelection.tsx
src/entries/popup/components/_dev/ClearStorage.tsx
src/entries/popup/handlers/importWalletSecrets.ts
src/entries/popup/handlers/wallet.ts
src/entries/popup/hooks/useAuth.tsx
src/entries/popup/hooks/useExpiryListener.ts
src/entries/popup/pages/settings/privacy/walletsAndKeys/recoveryPhrase/recoveryPhraseVerify.tsx
src/entries/popup/pages/walletSwitcher/chooseWalletGroup.tsx

Fixes BX-####
did some research about SessionStorage quota and [there's actually a 10MB limit](https://developer.chrome.com/docs/extensions/reference/storage/#property-session) but for a normal user we store less than 20kb.
However there's 2 keys that can grow unlimitedly during the session which are:
- rateLimit (per dapp) - this stores a key for the host and a timestamp for every dapp that you have connected to in the current browser's session
- queuedEvents:  this are all the tracking event from the service worker that we put in memory to be able to send it to the server through the popup (since we can't do it directly from the service worker)
I highly doubt any of these two is a real offender but anyways I'm taking two actions:
- Replaced our direct usage of …

Storage refactor

---

src/core/resources/_selectors/assets.ts
src/core/state/userChains/index.ts
src/core/utils/chains.ts
src/core/utils/userChains.ts
src/entries/popup/components/SwitchMenu/SwitchNetworkMenu.tsx
src/entries/popup/hooks/useInfiniteTransactionList.ts
src/entries/popup/hooks/useUserChains.ts
src/entries/popup/pages/settings/networks.tsx

Fixes BX-1115
Fixes BX-1113
the was an error while saving chain orders in state
in networks settings we only have mainnet chains to reorder and enable/disable but we were updating the order in an array of all chains, testnets and mainnets, so the filtering of the chains was messed up on networks modal, assets and txs
plz check the tickets, i've tried to break it but looking ok now

fix: testnet fixes

---

src/design-system/components/AnimatedRoute/AnimatedRoute.tsx
src/entries/popup/components/TestnetMode/TestnetBar/TestnetBar.tsx
src/entries/popup/components/WindowStroke/WindowStroke.tsx

Fixes BX-1119
addressing ticket
https://www.loom.com/share/d0f50a9ea7ea438cb7a8101289a90571

fix: show testnetbar condition

---

src/core/resources/_selectors/assets.ts
src/core/state/userChains/index.ts

Fixes BX-####
filtering assets by network broke, so any change on networks settings weren't filtering assets correctly, this pr fixes that

fix: asset filtering by networks settings

---

e2e/serial/dappInteractions/2_dappInteractionFlow.test.ts
src/analytics/event.ts
src/core/utils/assets.ts
src/core/utils/chains.ts
src/entries/background/handlers/handleProviderRequest.ts
src/entries/popup/components/CoinIcon/CoinIcon.tsx
src/entries/popup/pages/home/Tokens.tsx
src/entries/popup/pages/messages/ApproveAppRequest.tsx
src/entries/popup/pages/messages/WatchAsset/WatchAssetActions.tsx
src/entries/popup/pages/messages/WatchAsset/WatchAssetInfo.tsx
src/entries/popup/pages/messages/WatchAsset/index.tsx
static/json/languages/en_US.json

Fixes BX-1075
- Adds support for `wallet_watchAsset`
- First we try to use the session chain Id if there's one, if not, we look at the host and we know the block explorers for some networks. If we can't figure it out we default to mainnet and the user can switch it. See link below.
https://recordit.co/LakhR5U4Q3

walllet_WatchAsset

---

src/core/references/shortcuts.ts
src/entries/popup/pages/home/NFTs/DisplayModeDropdown.tsx
src/entries/popup/pages/home/NFTs/NFTDetails.tsx
src/entries/popup/pages/home/NFTs/NFTs.tsx
src/entries/popup/pages/home/NFTs/SortDropdown.tsx

Added support for keyboard navigation on the gallery page and the details page. Also added shortcuts that activate when the NFT dropdowns are in use.
PoW: https://recordit.co/ICzDbgfbGh
Make sure the gallery and details pages are navigable with the keyboard and that the 1/2 keys work when activating the dropdown.

[BX-1095][BX-1096] NFT Keyboard Nav + Shortcuts

---

src/entries/popup/pages/messages/DappScanStatus.tsx
src/entries/popup/pages/messages/RequestAccounts/RequestAccountsInfo.tsx
src/entries/popup/pages/messages/SendTransaction/SendTransactionsInfo.tsx
src/entries/popup/pages/messages/Simulation.tsx
src/entries/popup/pages/messages/useSimulateTransaction.tsx
static/json/languages/en_US.json

Fixes BX-####
https://rainbowhaus.slack.com/archives/C04M9BUPQP6/p1701375797969259

warn malicious transaction

---

src/core/state/currentSettings/flashbotsEnabled.ts

Fixes BX-####
last week i was using a lot feature flags, but every time i reloaded the extension i had to setup the feature flags i was trying to use because state wasn't able to rehydrate

fix: missing migration

---

package.json
src/core/graphql/config.js
src/core/graphql/index.ts
src/core/graphql/queries/ens.graphql
src/core/resources/ens/ensRegistration.ts
src/entries/popup/pages/home/NFTs/NFTDetails.tsx
static/allowlist.json
static/json/languages/en_US.json
yarn.lock

Figma link (if any): https://www.figma.com/file/hzfwKOddfRmeVO4KUsG9wM/Rainbow-BX?type=design&node-id=8127-263102&mode=design&t=P36zv51ZbKE5GZDM-0
The nft details page now displays registration info in place of the price section.
PoW: https://recordit.co/uFOZyEB6aK
Visit NFT details for ENS names, then make sure "Registered on" and "Expires in" displays correctly.
For documentation's sake: this is part two of BX-1102. The profile info was merged previously.

[BX-1102] Ens Registration Info

---

src/entries/popup/pages/home/TokenDetails/PriceChart.tsx
src/entries/popup/pages/home/TokenDetails/TokenDetails.tsx

Fixes BX-####
leaves space for the chart if it should have data (not testnet) and adds back favorite and more options on top
before / after
(aave chart data was cached on the before vid, but you can see the shift later with kwenta)
https://github.com/rainbow-me/browser-extension/assets/6232729/bfb2da5b-8366-49b1-8f50-89289a6ea977
https://github.com/rainbow-me/browser-extension/assets/6232729/933823a9-9505-4699-a253-99ed1423da82

fix token details ui shift

---

src/core/resources/nfts/nfts.ts

Prevents catastrophic nft bug
Make sure NFTs show up when IS_TESTING = 'false'

[BX-1155] Prevent Test Data Override

---

src/core/resources/nfts/nfts.ts

In cases where we filtered out 50/50 polygon collections in a simple hash collections call, we would then proceed with the remaining logic and pass in an empty collection id array. This would sometimes cause duplicate NFTs to appear in the collection.
This was fairly uncommon and didn't always happen so it's hard to illustrate a before and after. Please check that the logic looks alright and ensure you don't happen to run into the issue.

Prevent Periodic NFT dups

---

src/core/resources/assets/customNetworkAssets.ts
src/core/utils/numbers.ts
src/entries/popup/pages/home/TokenDetails/PriceChart.tsx

Fixes BX-####
We had a bug that we were only calculating prices for native assets on unsupported networks.
This PR fixes it.
Before
After

improve price discovery on l2s (unsupported networks)

---

src/core/resources/assets/customNetworkAssets.ts
src/entries/popup/hooks/useCustomNetworkAsset.ts
src/entries/popup/hooks/useGas.ts
src/entries/popup/hooks/useNativeAsset.ts
src/entries/popup/pages/home/TokenDetails/TokenDetails.tsx
src/entries/popup/pages/send/ReviewSheet.tsx

Fixes BX-1194
- adding send checks for custom rpcs
- fetching native assets for tx fee, there was a bug where users with a token balance but no native asset balance would see "undefined" as tx fee when trying to send a token since we were filtering out native assets with balance 0

send customrpc checks

---

src/entries/background/handlers/handleProviderRequest.ts
src/entries/popup/components/SwitchMenu/SwitchNetworkMenu.tsx
src/entries/popup/pages/messages/AccountSigningWith.tsx
src/entries/popup/pages/settings/rpcs.tsx

Fixes BX-1203
Fixes BX-1204
Fixes BX-1205

fix: networks fixes

---

src/entries/popup/pages/settings/rpcs.tsx

Fixes BX-1207
Default RPCs can't be deleted (mainnet and testnet)
http://recordit.co/50RpNzcXu6

Prevent default rpc deletion

---

src/entries/popup/pages/home/Points/PointsDashboard.tsx

Fixes BX-####
still a long way to go before we need to truncate this number so I think we can keep it as `<Text />` and maybe later find a workarond for `<TextOverflow />` when it becomes a real issue

points fix clipping text shadow

---

src/entries/popup/hooks/send/useSendAsset.ts
src/entries/popup/hooks/useVisibleTokenCount.ts
src/entries/popup/pages/home/Tokens.tsx

Fixes BX-1216
The assumption the assets array was already sorted before deduping is wrong since assets with no balance are randomly sorted at the end.

Fix asset deduping

---

src/entries/popup/pages/walletSwitcher/index.tsx

This now auto-focuses:
These can now be keyboard nav'd:
<video src="https://github.com/rainbow-me/browser-extension/assets/41711440/7dc81c31-8a86-4ada-8fe1-63c13db0ce54" >

[BX-1258] Make wallet search autoFocus + buttons keyboard nav friendly

---

src/entries/popup/components/TransactionFee/TransactionFee.tsx

Fixes BX-####
adding back custom gas only for mainnet introduced here https://github.com/rainbow-me/browser-extension/commit/488bb88b8f4d1444299affc0178113ab1d07bd44#diff-946bbcf208d616f064d91ab5f8614978c455f259c4811d8d77cfbea94d40d4a3L207

fix: custom gas for mainnet only

---

src/core/state/currentSettings/analyticsDisabled.ts

Fixes BX-####
- added browser check to default `analyticsDisabledStore` state for anonymized tracking
- default tracking toggle on Firefox

fix: disable anonymized collection by default on firefox

---

.github/actions/firefoxTestsSetup/action.yml
.github/workflows/build.yml
e2e/parallel/settingsFlows.test.ts
e2e/parallel/shortcuts-settings.test.ts

- Updated script to point to a specific version of ff dev edition.
- Changes to the `SettingsFlows` test and `ShortcutSettingsFlows` were due to the default toggle behavior being changed on Firefox while these tests were broken.

Updated script to point to a specific version of ff dev edition

---

src/entries/popup/components/AddressDisplay.tsx

Fixes BX-1305
The 'to' field on txn details when it was a contract was missing the `wrap={false}`
| Before | After |
|--------|-------|
| <img src="https://github.com/rainbow-me/browser-extension/assets/41711440/386ea3f9-9beb-4adf-b06b-fe084e8ff13d" width="363" alt="Screenshot 2024-02-06 at 2 14 36 PM"> | <img src="https://github.com/rainbow-me/browser-extension/assets/41711440/b119f308-6e94-48d2-9026-73497cf1c11d" width="363" alt="Screenshot 2024-02-06 at 2 14 36 PM"> |

Missing wrap={false} on activity details > contract address 

---

CHANGELOG.md

- You can now remove a Wallet Group in Settings to cleanup your unused wallets. Always make sure to backup your Secret Recovery Phrase first #1331
- Added Custom Network autofill support for Blast and Redstone Holesky #1373 #1358
- Removed support for deprecated Zora Goerli testnet #1367
- Avalanche is now fully supported in Rainbow, so you'll now see any assets you own on Avalanche, and can easy Send, Swap, Bridge, or interact with Avalanche dApps right out of the box #1307
- You can now see your current Token and NFT Approvals, and revoke each contract approval with 1-click from the Approvals menu in Settings #1322
- NFTs can now be easily sent to another wallet from the NFT Details interface or by right-clicking on an NFT in your NFT Gallery #1323 #1334
- You can now report spam NFTs …

changelog: v1.4.8 and v1.4.12

---

src/entries/popup/pages/settings/walletsAndKeys/walletsAndKeys.tsx

- Right click could direct to secret phrase reveal on HW wallets
- This just hides the button on hw wallets
<video src="https://github.com/rainbow-me/browser-extension/assets/41711440/45ba08f0-8f77-4bff-9184-4e29a36cb53e">

Remove secret phrase option on right click context - HW wallets

---

src/entries/popup/pages/messages/Simulation.tsx

Fixes [BX-1275](https://linear.app/rainbow/issue/BX-1275/reversed-arrows-and-colors-in-transaction-details)

BX-1275 Simulation reverse arrows and colors

---

e2e/serial/swap/1_swapFlow1.test.ts
e2e/serial/swap/2_swapFlow2.test.ts
e2e/serial/swap/3_shortcuts-swapFlow.test.ts
src/entries/popup/hooks/swap/useSwapInputs.ts
src/entries/popup/pages/swap/index.tsx

Selecting highest balance assets and setting max value by default. This behavior is overridden by `selectedToken` flows and saved swap values.
PoW: https://recordit.co/h5tD15KHoJ
Ensure the new defaults populate when navigating directly to swap with no saved values.

[BX-1331][BX-1332] Swap Default Values

---

CHANGELOG.md

- Blast is now supported in Rainbow, with Swap and Bridge support coming soon #1379
- You can now Pin and Unpin tokens with a hold-click to keep them at the top of your Tokens list #1370
- Hardware Wallets can now be Unpaired from the Wallets & Keys menu in Settings #1372
- When Bridging assets, you can now right-click on a pending transaction to track the status on the Socketscan explorer #1377
- Swaps are even faster now that we automatically populate your input token and provide a default amount #1378
- Updated Weekly Points Overview with new line items for Referrals and Bonus Redemptions #1389
- Removed deprecated Optimism Goerli network #1351
- Resolved an issue where some wallets were missing in the Send wallet list #1368
- Fixed an issue where the "Reveal Secret Phrase" option …

changelog: v1.4.22

---

src/core/resources/assets/customNetworkAssets.ts
src/entries/popup/hooks/useNativeAsset.ts
src/entries/popup/hooks/useVisibleTokenCount.ts

Fixes BX-1350
last week fixing blast i made this change https://github.com/rainbow-me/browser-extension/pull/1383/files#diff-3b6eb6e4c37dcc8c725f157d7953e3de4245db86d2724ccd45939fba1793bd62R223 to emulate what backend returns as uniqueId for native asset
that was correct but i didn't change it in the method that gives us the native asset while estimating gas https://github.com/rainbow-me/browser-extension/pull/1405/files#diff-4fd4cdb2833891791c48304800a1085b7c1c170b44e79c2121a5e3d701f7ce65R65 so native asset was undefined for custom networks, causing the issue
I updated all instances of this to have custom native tokens in the same format as backend

fix: BX-1350

---

src/design-system/components/Box/ColorContext.tsx
src/entries/popup/components/AppConnection/AppConnectionNudgeBanner.tsx

Fixes BX-1358
change introduced here https://github.com/rainbow-me/browser-extension/pull/1003 was making the black color to adjust to a gray since the contract with dark theme was low, which makes sense but here we're using it with avatar color as background
so i added a flag `respectColor` to skip that color treatment if is present

fix: BX-1358

---

src/entries/popup/pages/home/Activity/ActivityDetails.tsx

Fixes BX-####
`formatEther('0x0')` was causing the crash
https://rainbowhaus.slack.com/archives/C04M9BUPQP6/p1710725711853419

fix: airdrop tx detail crash

---

src/entries/popup/pages/send/ReviewSheet.tsx

The L2 send checkbox has been removed if you are sending funds to yourself.
PoW: 
Ensure the L2 warning no longer appears when sending to your own wallets.

[BX-1334] fix: remove l2 check when sending to self

---

e2e/serial/send/2_shortcuts-sendFlow.test.ts
src/entries/popup/components/ContextMenu/ContextMenu.tsx

Preventing radix from calling onSelect when a context click overlaps with the incoming menu.
https://www.loom.com/share/6e85c73529e54aa884bd9db6b0ea16bb
Make sure to use the popup. I don't think this is a reproducible issue in fullscreen. Just click a bunch in an area that you know will overlap with the incoming context menu.

[BX-1367] Right-click accidental pass-through actions

---

src/entries/popup/hooks/useRestoreNavigation.ts

Supporting nav restoration for the activity details modal.
PoW: https://recordit.co/ZZx4o43VCE
Test that you are returned back to activity details if you close the popup while it's being presented

[BX-1364] fix: support nav restoration for modal with route params

---

src/entries/popup/components/ExternalImage/ExternalImage.tsx
src/entries/popup/pages/home/NFTs/NFTThumbnail.tsx

Reducing Imgix usage among trusted sources for NFT Thumbnails.
Ensure we have no image regressions.

[BX-1349] chore: avoid signing nft thumbnail img src when possible

---

src/core/utils/assets.ts

Fixes BX-####
fixing https://rainbowhaus.slack.com/archives/C044WE28BTK/p1711713603065009
crash was happening on activity for nfts, where `bridgable` didn't exist

fix: empty activity

---

src/entries/popup/components/AppConnection/AppConnectionWatcher.tsx

Fixes BX-####
found this issue introduced here https://github.com/rainbow-me/browser-extension/pull/1404/files
https://github.com/rainbow-me/browser-extension/assets/12115171/2f02ba34-8d13-4a47-8b63-1a5d4437d260
you can see the connection banner for a second while the login screen is showing up
now is fixed, it doesn't appear
https://github.com/rainbow-me/browser-extension/assets/12115171/e409dd5d-9166-4ed2-96d6-5df0f58a9f22

fix: connection banner visible when on lock screen

---

src/core/references/gasUnits.ts
src/core/types/search.ts
src/core/utils/assets.test.ts
src/entries/popup/hooks/useSearchCurrencyLists.ts

Fixes BX-####
fixes https://rainbowhaus.slack.com/archives/C02C8JQ313N/p1712086754141749
isRainbowCurated is deprecated so i updated it to use isVerified

fix: deprecate isRainbowCurated for swap assets

---

src/core/providers/proxy.ts

Fixes BX-####
backend request to only pass custom_rpc for not supported networks

fix: dont use custom_rpc param

---

src/core/resources/_selectors/assets.ts
src/entries/popup/components/AccountItem/AccountItem.tsx
src/entries/popup/components/AppConnection/AppConnectionWalletItem/AppConnectionWalletItem.tsx
src/entries/popup/hooks/useUserAssetsBalance.ts

Fixes BX-1384
https://github.com/rainbow-me/browser-extension/assets/53529533/cd4a431b-a5cf-484b-abef-2262ab930c4c
- Make sure token balance is subtracting when hiding them. You should see that in homepage, change wallet page and switch wallet popup (all of them are shown in video)
- Make sure to test with custom assets too

chore: subtracting token balance if token is hidden

---

src/entries/background/index.ts
src/entries/popup/App.tsx

Fixes BX-1379
background was trying to get remote config causing the issue described in ticket
with this pr we'll get whether proxy is enabled from popup to set up wagmi client when user is interacting with popup via background-popup messenger

fix: BX-1379

---

e2e/serial/send/3_customNetworks.test.ts

e2e appears to be failing across the board due to zkevm testnet RPC not responding. I attempted to find a better RPC url, but those did not work either. I replaced this test with telos testnet.
🤞 e2e passes

fix: swap out zkevm testnet

---

src/core/resources/positions/index.ts
src/core/utils/assets.ts

Added requests for defi positions.
Example of parsed data after fetching defi positions:
```js
{
"1": {
"positions": [
{
"type": "blur",
"network": "mainnet",
"deposits": [
{
"address": "eth",
"uniqueId": "eth_1",
"chainId": 1,
"chainName": "mainnet",
"mainnetAddress": "eth",
"isNativeAsset": true,
"native": {
"price": {
"change": "1.86%",
"amount": 3580.41,
"display": "$3,580.41"
},
"balance": {
"amount": "71.6082",
"display": "$71.61"
}
},
"name": "Ethereum",
"price": {
"value": 3580.41,
"changed_at": 1711640978,
"relative_change_24h": 1.8550864815657597
},
"symbol": "ETH",
"type": "native",
"decimals": 18,
"icon_url": "https://rainbowme-res.cloudinary.com/image/upload/v1668565116/assets/ethereum/eth.png",
"colors": {
"primary": "#808088",
"fallback": "#E8EAF5"
},
"networks": {
"1": { …
```

[BX-1373] feat: add defi position requests and data handling

---

src/entries/popup/components/ExternalImage/ExternalImage.tsx
src/entries/popup/pages/home/Activity/ActivityIcon.tsx

Fixes BX-####
I tested and the [bx-1380](https://linear.app/rainbow/issue/BX-1380/externalimage-undefined-fetching-error) keeps being fixed with these changes :)
before/after 
some fallbacks didn't show

Fix <ExternalImage />

---

src/entries/popup/pages/settings/settings.tsx
src/entries/popup/pages/settings/transactions.tsx

We recently changed the order of the settings list items. We need to alter the border radius on a few items to match the design.
before:
after:

[BX-1399] fix: tweak border radius on settings list items

---

src/entries/popup/hooks/useNativeAssetForNetwork.ts

BX-1401
Grabbing correct unique id strings for BNB and MATIC
PoW:
https://polygonscan.com/tx/0x9b246c5ecfcb6169e1ee5d903b1216b0722a9a1cc1e42a5f1fa0647045103d6d
https://bscscan.com/tx/0xbfe6f0db3625f655a2730ac4f71dc29171a68d823f90ae3d3261f741ebc78e0f
Make sure polygon and bsc sends work

fix: native asset strings for non eth gas tokens (MATIC + BNB)

---

e2e/serial/send/3_customNetworks.test.ts
src/entries/popup/pages/home/NetworkMenu.tsx

Fixes BX-####
fixing badge, not sure when it broke
before
now

fix: app connection header badge

---

src/entries/popup/pages/messages/Simulation.tsx

Fixes BX-####
i'm seeing this error
there's a `0` value in black when `assetPrice` is 0, so i'm `!!assetPrice`

simulation asset price when is 0

---

src/core/state/rainbowChains/index.ts
src/core/utils/migrate.ts

Fixes BX-1420
adding zora back to the state if is missing for these users
details and POW  video in ticket

fix: add zora again if is missing

---

src/entries/popup/components/CommandK/useSearchableTokens.ts
src/entries/popup/hooks/send/useSendAsset.ts
src/entries/popup/hooks/useVisibleTokenCount.ts
src/entries/popup/pages/home/Tokens.tsx

Fixes BX-1421
details of bug in ticket
maybe this is still happening since we're combining assets in an array directly from assets and customNetworkAssets, with this pr we'll only get one per uniqueId so there won't be duplicates for sure

combined assets by uniqueId

---

src/core/references/index.ts
src/core/resources/assets/assets.ts
src/core/state/favorites/index.ts
src/entries/popup/hooks/swap/useSwapAssets.ts
src/entries/popup/hooks/useNativeAssetForNetwork.ts
src/entries/popup/hooks/useNativeAssets.ts
src/entries/popup/pages/home/Tokens.tsx
src/entries/popup/pages/messages/Simulation.tsx

Fixes BX-1428
we were picking ETH as native asset for degen making prices go crazy
since degen doesn't exist in mainnet i had to refactor the way we fetch native assets, so we now `requestMetadata` of the native asset address on the chain together with the chainid, before we were just picking the assets for mainnet making it impossible to fetch native assets that don't exist in mainnet like degen
plz make sure all chains work fine, attached a video of my qa
https://www.loom.com/share/b6328a49d83b4d29b50f79d8e7ff986d

fix degen native asset

---

CHANGELOG.md

- Broadened coverage of our network explainers as you interact with assets across alternative L1s, and Ethereum L2s and L3s #1490
- Resolved an issue with missing prices for some token pairs in our Swap interface #1505
- Bumped `@solana/web3.js` version to `1.90.2` to resolve CI audit issue #1503
- Your POAP collection is now available in the NFT Gallery #1469
- Degen Chain is now fully supported in Rainbow. Send, Swap, and interact with Degen dApps with Rainbow #1476
- You'll now see USD or preferable currency estimates for each Transaction Preview, so that you can at a glance understand the real cost of a transaction #1481
- Enabled Transaction Previews and simulation for Contract deployments #1485
- It's now even easier to Speed up and Cancel a transaction #1495
- Shortcuts on now …

changelog v1.4.67, v1.4.65

---

src/core/state/rainbowChains/index.ts
src/core/state/userChains/index.ts
src/core/utils/migrate.ts

Fixes BX-1427
deatils in ticket
- degen not being active by default fixed here https://github.com/rainbow-me/browser-extension/commit/cfff9c5e2ec84ebbc01b16a391c5d2a604f303ee
- avoid rpc duplication fixed here https://github.com/rainbow-me/browser-extension/commit/f8ac1b7f7fd51246f1c6fa0d4150907df7a6452e we were just adding a new rpc without checking the old rpc is the same than the new one
- adding a migration to add degen rpc in case is missing https://github.com/rainbow-me/browser-extension/commit/17952ad3dd74d992fc62d7996c3c2a09344c2956

degen issues

---

CHANGELOG.md

- Added auto-fill support for Redstone and Rootstock networks in the Add Network flow #1508
- Resolved duplicate instances of tokens like `DEGEN` when Rainbow introduces rich metadata for a new network #1499
- Resolved a white flash on launch for users in dark mode #1509
- Improved quote price estimates for Swaps on Degen Chain #1512

changelog: v1.4.73

---

src/entries/popup/pages/home/Points/PointsDashboard.tsx
src/entries/popup/pages/home/Points/WeeklyPointsOverview.tsx

Keyboard navigation added to the points dashboard and the weekly earnings modal
https://www.loom.com/share/41a8d23a3c0a4827937a62d5f528906e
Traverse the points screen with the keyboard. Cards with onClick/onTap handlers should work when pressing ENTER.

[BX-1434] feat: add keyboard navigation to the points dashboard

---

src/entries/popup/pages/messages/BottomActions/index.tsx
src/entries/popup/pages/messages/SignMessage/SignMessageActions.tsx

Shrinking cancel button and letting confirmation CTA grow when waiting for hw wallet.
Make sure the confirm button grows to display the waiting for device copy when signing with hardware wallet

[BX-1371] fix: increase cta width when waiting for device

---

src/core/resources/transactions/consolidatedTransactions.ts
src/core/resources/transactions/transaction.ts
src/core/state/transactions/customNetworkTransactions/index.ts
src/design-system/components/BottomSheet/BottomSheet.tsx
src/entries/popup/hooks/useInfiniteTransactionList.ts
src/entries/popup/hooks/useTransactionListForPendingTxs.ts
src/entries/popup/hooks/useWatchPendingTransactions.ts
src/entries/popup/pages/home/Activity/ActivityDetails.tsx
src/entries/popup/pages/home/Approvals/Approvals.tsx

Fixes BX-####
- activity details sheet insta shows on clicking an activity (before was waiting for loading), now it shows with the data we got and updates as more data comes
- removed `testnetMode` from the consolidatedTransactionsQueryKey as it was not used in the query itself and I didn't find a reason to have it in the query key lmk if Im mistaken
- refactored a lil bit the `useTransaction` hook, aggregated into a single useQuery for either supported or unsupported BE networks and added some more info we could find when fetching the tx data from the provider

Activity details loading

---

CHANGELOG.md

- More reliable and accurate slippage threshold estimates are now available for Swaps #1502
- You can now navigate the Points dashboard and Weekly Drops with your Keyboard #1522
- Resolved issues for users that experienced a missing RPC and failed transactions on Degen Chain L3 #1518
- Fixed an issue where Speed up and Cancel transaction would not appear in the Activity list #1413
- Improved Ledger connection reliability to reduce signing timeouts #1494
- Resolved a UI display issue when Signing transactions for Hardware Wallets #1524
- Fixed text overflows for long wallet names on dApp Connection prompts and Transaction Previews #1525 #1507
- Improved performance when launching Activity Details for a transaction #1519
- Fixed shortcuts handling on the Backup Reminders and added `esc` …

changelog: v1.4.81

---

src/entries/popup/hooks/useNativeAsset.ts
src/entries/popup/hooks/useNativeAssetForNetwork.ts
src/entries/popup/pages/messages/SendTransaction/SendTransactionsInfo.tsx

Fixes BX-1450
Fixes BX-1451
updated the way we get native assets from `useNativeAsset`
check ticket for more details

fix: missing native asset name

---

src/entries/popup/pages/home/Activity/ActivitiesList.tsx
src/entries/popup/pages/home/Tokens.tsx

Fixes BX-####
pretty sure the bug was in the way we were using framer motion `layoutId` to transition between lists, the idea was set `layoutId` to the list row index so when we change tabs between activities and tokens, the same index rows would transition smoothly
the issue is when we are adding or reordering stuff in each list, like tx A is index 1 in the list, a new pending tx B is added, now B is index 1, so framer motion is trying to animate tx row A to B but it shouldn't!! 
that's the reason we don't use index as the `key` in react, we shouldn't use as `layoutId` either
to replace the previous transition I added this one
https://github.com/rainbow-me/browser-extension/assets/6232729/670ca442-776b-4228-a48f-d29e4e7b01d3

probably fix overlapping activities

---

CHANGELOG.md

- Fixed missing gas token names on the Transaction Previews for Degen Chain and additional L2 and L3 networks
- Removed deprecated Polygon Mumbai network #1477
- Temporarily altered Rudderstack flush behavior to mitigate event drops #1533

changelog: v1.4.84

---

e2e/parallel/shortcuts-home.test.ts
src/entries/popup/hooks/useActivityShortcuts.ts
src/entries/popup/hooks/useKeyboardShortcut.ts

Fixes BX-1465
If you try to go to different menus in Cmd+K and then click backspace shortcut you won't get navigated back to where you was. There is also a bug where you can't copy NFT token id using `c` shortcut.
Open Cmd+K menu -> navigate to "My Wallets" -> hit backspace shortcut and you should be able to get navigated back to the default Cmd+K view

fix: `useKeyboardShortcut` not working with Cmd+K backspace shortcut

---

e2e/helpers.ts
e2e/parallel/commandKFlow.test.ts
src/design-system/components/TextOverflow/TextOverflow.tsx
src/entries/popup/components/CommandK/CommandRows.tsx
src/entries/popup/components/CommandK/references.ts
src/entries/popup/components/CommandK/useCommands.tsx
src/entries/popup/components/CommandK/useSearchableContacts.ts
static/json/languages/en_US.json

Fixes BX-1469, BX-1467, BX-1462, BX-1461, BX-1460, BX-1459, BX-1458
- "Send to this wallet" is added in "My Wallets". You can now send tokens to your owned / imported wallets with Cmd+K.
- Removed "Watch this wallet" for contacts so there is less confusion between "Contacts" and "Watched wallets" are.
- Tweak command activation sub-titles to contacts menus in Cmd+K
- If you are on a watched wallet or if the contact wallet has the same wallet as your current connected wallet then we'll display a "View" shortcut instead of redirecting to send page when selecting a contact in Cmd+K.
- Hide "Add contacts" if you're on a watched wallet

chore: contacts tweaks, send to wallet flow and Cmd+K e2e test coverage

---

src/design-system/components/Box/Box.tsx
src/design-system/components/Text/Text.tsx
src/entries/popup/components/SeedPhraseTable/SeedPhraseTable.tsx
src/entries/popup/components/SeedVerifyQuiz/SeedVerifyQuiz.tsx
src/entries/popup/pages/settings/walletsAndKeys/privateKey/privateKey.tsx

Fixes BX-1466
Some browser like microsoft edge and google chrome can translate words / letters to another language, this can happen if user wishes to use "translation" feature in the browser setting. The only problem with that is when seed phrases appear they get translated to another language instead of the english language, same with private keys the letters can be translated to another letter language.
**Before (Microsoft edge):**
**After (Microsoft edge):**
- You can use google translate feature in google chrome or use microsoft edge translation feature by going to settings -> languages -> "Offer to translate pages..." and remove english as preferred language and choose any other language which you'd want to translate.
- Try creating a new wallet group and see if seed phrases are not …

fix: auto browser language translation for seed phrases / private keys

---

CHANGELOG.md

- You can now add, remove, and manage Contacts in the Magic Menu with Cmd+K #1526 #1539 #1542 #1543
- Instant bridging routes are now available in Rainbow for many core tokens and networks via the Relay Protocol #1531
- Search result priority ordering improvements in the Magic Menu for commands, tokens, and more #1543
- Improved translation coverage for the Magic Menu #1537
- Resolved an issue where pending transactions could visually overlap in Activity #1532
- Blocking auto-translation attempts in some browsers while interacting with your Secret Recovery Phrase #1544
- Fixed an issue with `ESC` keyboard dismissals for the Token Details card
- Fixed an issue for some dApps like Etherscan that required triggering a connection request upon switching networks #1536
- Resolved interaction …

changelog: v1.4.97

---

src/core/resources/gas/meteorology.ts
src/core/resources/gas/providerGas.ts
src/core/utils/gas.ts

Fixes BX-1457
original sepolia issue was happening because we were using mainnet gas prices from meteorology, instead we should get gas fees from provider,
so
- testnets are now getting fees directly from provider since they're not supported by meterology
- testnets and custom networks where we don't have meteorology support will get gas fees from provide (which is the case in prod rn) with the difference that now we're getting eip1559 gas fees from network if supported for better gas fees

fix: testnet gas

---

src/core/references/chains.ts
src/core/resources/gas/meteorology.ts

Fixes BX-1484
added blast to meteorology supported chains

fix: blast gas

---

src/entries/popup/components/QuickPromo/QuickPromo.tsx

Fixes BX-1456
- Some languages like Russian had text overflow issues on promotion banners. The pages that were impacted were home, switch wallet and networks page.
**Before:**
**After:**
- Make sure the banner doesn't cause text overflow issues on different languages

fix: promotion banner text overflow (i18n)

---

src/core/resources/search/tokenSearch.ts
src/entries/popup/hooks/swap/useSwapAssets.ts
src/entries/popup/hooks/useSearchCurrencyLists.ts
src/entries/popup/pages/swap/SwapTokenInput/TokenDropdown/TokenToBuyDropdown.tsx
src/entries/popup/pages/swap/SwapTokenInput/TokenToBuyInput.tsx
src/entries/popup/pages/swap/index.tsx

Fixes BX-1330
- Swap page now supports contract address search. It'll also search on all supported networks instead of single choosen network.
https://github.com/rainbow-me/browser-extension/assets/53529533/2f61def6-9a65-4fda-9832-cfee73c18ab4
- Go to swap page
- Paste in any token contract address and make sure it searches the token on all supported networks. For example `0x50c5725949a6f0c72e6c4a641f24049a917db0cb` should search for DAI on base and LYRA on optimism.
- Make sure you don't see "Filter by network" dropdown option because we search for all networks.
- Make sure the swap flow works the same as usual.

feat: swap contract address search support

---

src/entries/popup/hooks/useUserAssetsBalance.ts

Fixes BX-1490
- Fixed an issue where `NaN` would show up in tab bar from home page
**Before:**
**After:**

fix: `NaN` shown in tokens tab bar

---

lavamoat/build-webpack/policy.json
src/core/utils/transactions.ts

Fixes BX-1483
we're now showing the correct address
check a send tx and see if address is the actual recipient and not the contract address, for tokens and nfts

fix: parse tx to address in activity

---

src/entries/popup/hooks/useSearchCurrencyLists.ts

Fixes BX-1495
We don't check if the token is native or non native from destination chain. For example when bridging Degen on degen chain to Degen on base chain the quote will fail. It'll search for `0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE` instead of the Degen token address on base.
Here is a bug where user can't bridge Degen on degen chain to Degen on base chain
https://github.com/rainbow-me/browser-extension/assets/53529533/96f98e18-7e57-4cc7-b89d-01ccced77831
- Make sure you can bridge Degen on degen chain to Degen on base chain

fix: bridge quote not working for some tokens

---

src/core/resources/gas/gasData.ts
src/core/resources/gas/providerGas.ts

Fixes BX-1520
for chains that we don't officially support we currently have a provider `getFeeData` call, but it doesn't work very well, specifically foro zksync there's a different mechanism https://docs.zksync.io/zk-stack/concepts/fee-mechanism that. can be resumed using gasprice
so i'm deleting the old `getFeeData` call and only using the old  `getGasPrice`
tx sent https://explorer.zksync.io/tx/0x0fccc2a888c1b6e9be5d70c88c2c87f1717f702b8202c12f2ee1566da208737c
and the fee looks ok now

fix: provider gas

---

package.json
src/entries/background/handlers/handleProviderRequest.ts
src/entries/popup/pages/home/Tokens.tsx
yarn.lock

Fixes BX-1502
adding support for `wallet_revokePermissions`
it needs this one merged first https://github.com/rainbow-me/provider/pull/17
https://github.com/rainbow-me/browser-extension/assets/12115171/0e2742ca-b144-4afd-96c4-57d7b20bca5f

feat: wallet_revokePermissions

---

src/entries/popup/hooks/useHomeShortcuts.ts
src/entries/popup/pages/home/TokenDetails/TokenDetails.tsx

Fixes BX-1486
- Home shortcuts weren't unregistered in token details page. Technically it should be unregistered since token details  page is a whole new route / component, but we used token details page as a child route of the home route which didn't unmount the home shortcut listener.
- Make sure when you land in token details page you can copy address by pressing `C` shortcut and same with `P` for pin.

fix: home shortcuts not unregistered in token details

---

src/entries/popup/pages/home/Points/ClaimSheet.tsx

Fixes BX-1535
Saving initial claim values for display during confirmation
https://www.loom.com/share/3356fd33f65c48fbbaa0c293e659b39d
Make sure initial claim values appear on the confirmation screen

fix: cache initial claimable price

---

src/core/raps/actions/claim.ts
src/entries/popup/pages/home/Points/ClaimOverview.tsx
src/entries/popup/pages/home/Points/ClaimSheet.tsx

Prevent `<RainbowSlant />` from rerenders in claim overview and tweak console text timing slightly

fix: memoize rainbow text in claim

---

lavamoat/build-webpack/policy.json
src/analytics/event.ts
src/analytics/userProperties.ts
src/core/raps/actions/claim.ts
src/entries/popup/pages/home/Points/ClaimOverview.tsx
src/entries/popup/pages/home/Points/ClaimSheet.tsx
src/entries/popup/pages/home/Points/PointsDashboard.tsx
static/json/languages/en_US.json

Fixes BX-1528
TRACKED:
- Track event for Viewed Leaderboard
- Track event for Viewed Rewards 
- Track event for tapped Claim button
- Track event for Claimed
- Network selected Optimism Base Zora
- Claim amount USD
- Claim amount
- Track event for Shared Referral Link
- User identify event for `unclaimedBalance` and `unclaimedBalanceUSD`
- User identify event for `claimedBalance` and `claimedBalanceUSD`
Do they populate and do they cover the requested events?
I tested on rudderstack with dev key and it was working for me

stimmy analytics, additional ui fixes

---

src/core/firebase/remoteConfig.ts

Fixes BX-####
- turned `rewards_enabled` on by default to mitigate issues for users with VPNs that block Firebase APIs

chore: amend `rewards_enabled` default

---

lavamoat/build-webpack/policy.json
package.json
src/entries/inpage/index.ts

Fixes BX-####
`window.rainbow.providers` was only defined once at the beginning, so any updates to `rnbwWalletRouter.providers` won't be reflected in `window.rainbow.providers`, in which case were rainbow provider is `window.ethereum` the `window.ethereum.providers` would only have the first definition of `window.rainbow.providers` at the beginning 
EDIT
ended up removing `isMetaMask` flag when `announceProvider`

fix: window. rainbow providers

---

lavamoat/build-webpack/policy.json
src/core/raps/unlockAndCrosschainSwap.ts
src/core/raps/unlockAndSwap.test.ts
src/core/raps/unlockAndSwap.ts
src/core/utils/swaps.ts

Fixes BX-1554
we had checks only making `isNativeAssetUnwrapping` true in mainnet

fix: wrap unwrap in different chains than mainnet

---

src/entries/popup/utils/playSound.ts

Fixes BX-1563
- added `catch()` to `.play()` promise

fix: catch error when sound fails to play on firefox due to permissions

---

lavamoat/build-webpack/policy.json
src/core/utils/numbers.ts
src/entries/popup/pages/swap/SwapReviewSheet/SwapAssetCard.tsx
src/entries/popup/pages/swap/SwapReviewSheet/SwapReviewSheet.tsx

Fixes BX-1550, BX-121, BX-1551
- this PR effects the swap review cards and the swap review
- follow up PRs to follow changing this behavior elsewhere in the app
- numbers >= 1,000 are now abbreviated using K, M, B, T, etc.
New behavior:
- do large and small values round correctly on the review cards

Rounding large numbers

---

src/entries/popup/App.tsx

Disabled default behavior when we receive a `'wheel'` event with the `ctrlKey` field set to true.
Pretend I posted a video of nothing happening.
Attempt to zoom in on the application using the 2 finger double tap gesture on the touchpad.

[BX-1545] fix: prevent touchpad dbltap zoom

---

src/entries/popup/hooks/useTokenDetailsShortcuts.ts

Fixes BX-1565
From ticket:
"Goal:
Only register Token Details shortcuts when the context menu is visibile
Allow a user to select text and copy"
The shortcuts associated with the more options menu in token details now are only active when the dropdown is visible.
Make sure that token details does not intercept the 'C' key when the more options dropdown is hidden.

fix: disable activity details shortcuts without dropdown

---

src/entries/popup/pages/home/Points/utils.ts

Fixes BX-1287
Users with empty referral activity will now always see referral line items in the weekly summary even if empty ("none").
Ensure these line items appear for addresses with no activity for a given week.

fix: show referral and referral activity points when empty

---

src/entries/popup/pages/settings/customChain/addAsset.tsx

Fixes BX-1417
The custom asset draft for a particular network will wipe saved data after successful token addition. 
Add a custom asset to a network, then revisit the add asset form for the same network to ensure that the saved form data was wiped.

fix: wipe saved custom asset draft after addition

---

src/entries/popup/pages/home/Points/PointsDashboard.tsx

Fixes BX-1570
The total eth earned by rainbow users displayed on the points page is now restricted to 3 decimal places.
Check that this value does not exceed 3 decimal places.

fix: round total eth rewards to 3 decimals

---

src/design-system/components/TextOverflow/TextOverflow.tsx
src/entries/popup/pages/home/TokenDetails/About.tsx
src/entries/popup/pages/home/TokenDetails/PriceChart.tsx
src/entries/popup/pages/home/TokenDetails/TokenDetails.tsx

Fixes BX-####
- follow up to #1640
- mirrored `Text` component `selectionStyle` behavior and `cursor` and `user-select` to `TextOverflow`
- ensured all components in Text Details are selectable with appropriate accent color
<br>
<br>
<br>

fix: token details info text selection

---

src/core/types/transactions.ts
src/core/utils/transactions.ts
src/entries/popup/pages/home/Activity/ActivityDetails.tsx

Fixes BX-1438
We are now using BE values for explorer names and explorer urls in activity context menus. 
Explorer names + links in activity context menu and activity details more menu

feat: use BE explorer values for txs

---

src/entries/popup/components/CommandK/useSearchableENSOrAddress.ts

Fixes BX-1482
Searching for wallet address will show duplicates for Watching, Contact, and Owned wallets
**Before:**
**Now:**
Try adding a watched wallet and/or a contact wallet, and make sure that no additional result appear.

fix: duplicate wallet result in Cmd+K search

---

lavamoat/build-webpack/policy.json
src/core/types/transactions.ts
src/core/utils/transactions.ts

Fixes BX-1536
- replaced the 'from' row in claim transaction details with Rainbow + rainbow icon
- added app row to claim tx details
Eth reward claims should show rainbow in the from row and list rainbow in the app row.

Missing App field for ETH Rewards claim transactions, From address should be rich metadata for Rainbow

---

lavamoat/build-webpack/policy.json
src/core/resources/gas/meteorology.ts
src/core/resources/gas/providerGas.ts
src/core/state/gas/index.ts
src/core/utils/gas.ts
src/entries/popup/components/TransactionFee/CustomGasSheet.tsx
src/entries/popup/components/TransactionFee/TransactionFee.tsx
src/entries/popup/components/TransactionFee/TransactionSpeedsMenu.tsx
src/entries/popup/hooks/useGas.ts
static/json/languages/en_US.json

Fixes BX-1546, BX-1507
enabling custom gas in all networks for all txs types
https://www.loom.com/share/19d39fed3c1040c29ae00a41eddc8a81

feat: custom gas in all networks

---

CHANGELOG.md

- Resolved an issue with failing transactions when switching to an alternate RPC for a default network #1657
- Gas Speed defaults and Custom Gas settings are now available for all networks #1631
- You can now more easily access Approvals and Bridging with shortcuts in the Cmd+K Magic Menu #1637 #1629
- Transaction explorer links are now more accurate for each network, including support for RelayScan for bridges #1635
- You can now highlight and copy text and numeric values for Tokens and Activity transactions #1644
- Rainbow ETH Rewards claims are now properly labeled as Rainbow interactions in Activity Details #1633
- Resolved an issue with accurate balance discovery during wallet import #1634
- Resolved issues with RPC management for networks. You can now right-click on a custom RPC …

changelog: v1.5.23 to v1.4.130

---

src/entries/popup/components/QuickPromo/QuickPromo.tsx

Fixes BX-1537
Firefox had a font issue with `<span>` element. Now we manually set the font family and font size to the `<QuickPromo>` component.
**Before:**
**After:**
Go to firefox and make sure none of the promotion banner has a font issue.

promotion banner font issue (firefox)

---

src/entries/popup/hooks/swap/useSwapNativeAmounts.tsx

Fixes BX-1610
Related to: https://github.com/rainbow-me/rainbow/pull/6022
Re-added optional chaining on Quote object as the WETH/ETH unwrap/wrap path has different response type than normal swaps.
Did not take screen recordings - someone please verify.
Test ETH -> WETH and flip (WETH -> ETH)

Re-adding optional chaining for sellAsset and buyAsset on quote response

---

src/entries/popup/pages/home/Points/PointsDashboard.tsx

Fixes BX-1609
Passed border radius from <Card /> props to <Lens /> to fix navigation highlighting display issues and also removed a few things from the tab index that probably don't need to be there.
This screen could probably use some extra kb functionality + nav, but this PR just fixes the existing display issues.
Make sure that selecting the Last Week's Earnings card with the keyboard looks and behaves normally.

fix: add border radius to lens cmp wrapping cards

---

CHANGELOG.md

- Degen Mode is here to make Swapping even faster. Turn it on in Swap Settings to skip the review steps #1652
- Automatically defaulting ETH as the output for Swaps, and using Max values to reduce clicks #1622 #1653
- Swap values are now rounded to match the Rainbow App. Pasting an exact amount or Maxing will continue to function as expected #1656
- Added support for Ham and Cronos chains in Custom Networks #1658
- You'll now see Hardware Wallet identifiers for wallets in the Send flow #1659
- Token balances will now update in realtime alongside relevant transactions #1649
- Fixed an issue where Pending Transactions would sometimes disappear from Activity between submission and confirmation #1649
- Fixed an issue where Rainbow Rewards claim confirmations were not properly rendered #1668
- …

changelog: v1.5.32

---

audit-ci.jsonc

Fixes BX-####
- ignoring `GHSA-m95q-7qp3-xv42` DDOS vulnerability of `zod` used in `make-color-more-chill` dependency

ci: ignore GHSA-m95q-7qp3-xv42

---

src/entries/popup/hooks/swap/useSwapQuote.ts

We were not properly clearing swap data when a user cleared the input or manually typed '0' into the swap inputs.
PoW: https://www.loom.com/share/5415e6ba392f474489728d7a1a50cbf1
Reference the bugs detailed in the two attached tickets, but generally play the swap inputs and ensure that unnecessary market warnings are not displayed when clearing swap input data and that we don't see any wacky values displayed in the native currency display fields when swap input data is cleared from either input.

Fix BX-1641 & BX-1642

---

audit-ci.jsonc
e2e/serial/swap/1_swapFlow1.test.ts
e2e/serial/swap/2_swapFlow2.test.ts
lavamoat/build-webpack/policy.json
package.json
src/core/raps/unlockAndSwap.test.ts
src/core/utils/gas.ts
src/core/wagmi/clientToProvider.ts
src/entries/background/handlers/handleWallets.ts
src/entries/popup/pages/swap/SwapSettings/SwapSettings.tsx
yarn.lock

Fixes BX-4828
custom slippage wasn't working on prod so e2e was sending swaps with a very low slippage value
also edited e2e flow to correctly type values in slippage and swaps input to make e2e work

fix: custom slippage

---

scripts/networks.js
src/core/types/chains.ts
src/core/utils/backendNetworks.ts

Fixes BX-####
- added `internal` type to `BackendNetwork` type and ingestion query
- filtering out `internal` networks in prod, showing for `INTERNAL_BUILD` or `IS_DEV`

internal networks filtering

---

src/entries/popup/hooks/swap/useSwapReviewDetails.ts

Fixes BX-1647
- `sellAmountDisplay` and `buyAmountDisplay` could be undefined for `WETH` unwrap quotes
- Tested both Optimism WETH -> ETH and Degen Chain WDEGEN to DEGEN

fix: weth unwrap swap review undefined

---

lavamoat/build-webpack/policy.json
src/core/graphql/__generated__/metadata.ts
src/core/graphql/queries/metadata.graphql
src/core/resources/assets/externalToken.ts
src/core/resources/assets/userTestnetNativeAsset.ts
src/entries/popup/hooks/send/useSendValidations.ts
src/entries/popup/hooks/swap/useSwapReviewDetails.ts
src/entries/popup/hooks/swap/useSwapValidations.ts
src/entries/popup/hooks/useGas.ts
src/entries/popup/hooks/useNativeAsset.ts
src/entries/popup/hooks/useNativeAssetForNetwork.ts
src/entries/popup/hooks/useUserNativeAsset.ts
src/entries/popup/pages/home/Points/ClaimSheet.tsx
src/entries/popup/pages/home/Points/PointsDashboard.tsx
src/entries/popup/pages/messages/AccountSigningWith.tsx
src/entries/popup/pages/messages/SendTransaction/SendTransactionsInfo.tsx
src/entries/popup/pages/messages/useHasEnoughGas.ts
src/entries/popup/pages/swap/SwapReviewSheet/SwapReviewSheet.tsx

Fixes BX-1635
using metadata external token query to get native assets for all chains as described in ticket
now we have two different hooks for this:
- useNativeAsset:  that will give you a ParsedAsset object, that contains the price of the asset for stuff like tx fees
- useUserNativeAsset: that will give you a ParsedUserAsset object, that contains the wallet's balance

extend user native asset

---

lavamoat/build-webpack/policy.json
src/core/state/rainbowChains/index.ts
src/core/state/userChains/index.ts
src/core/utils/persistOptions.ts
src/entries/popup/hooks/useRainbowChains.ts

Fixes BX-####
Couple of issues are happening right now
For state userChains we could update `version` to `SUPPORTED_CHAINS.length` so if there's a new change we don't have to update the version number manually and zustand migrates automatically.
This works in `state/userChains` but it doesn't in `state/rainbowChains` because we're using `persistOptions` that doesn't allow this.
`persistOptions` needs to manually pass a new migration function on every version bump which is not ideal and is causing additional issues for this case in particular: if `rainbowChains` updates with a new chain, the migration doesn't pick it automatically, I had to add 
```
function v10(state: unknown) {
const rnbwState = state as RainbowChainsState;
rnbwState.rainbowChains = …
```

fix chain migrations

---

.github/actions/chromeTestsSetup/action.yml
e2e/serial/swap/1_swapFlow1.test.ts
lavamoat/build-webpack/policy.json
package.json
yarn.lock

- E2e is currently unable to run on local
- Greg's PR that added popular in rainbow indirectly caused a couple of these issues
- If a token is in the 'popular in Rainbow' section, it doesn't appear in other sections of the search. `gmx` sometimes appears here and sometimes doesn't. When greg merged his PR it wasn't so e2e was passing but now it is, so it failed. 
- to fix this, added a couple try / catch blocks when we search for this specific token
- added a couple of delays in areas i was seeing random sporadic failures as well.
- also bumping chromedriver / chrome version to match my local so I can run tests

e2e swap fixes, bump chromedriver

---

src/core/utils/copy.ts
src/entries/popup/pages/home/TokenDetails/About.tsx

When a user copies a token address to their clipboard, the copied address should be the proper checksummed version.
This is done by wrapping the address that is copied inside a `getAddress()` call from viem.
Test if the copied addresses of tokens are properly checksummed. 
This is my first time formally contributing to the codebase. I am not familiar with it and am not sure how to set up a local environment. Thus I just made the proposed changes to the best of my ability/knowledge. Glad to work through the problem to get the feature where it needs to be.
It is possible that this feature should be expanded to ANY address, rather than just token addresses.
Cheers!

Copy checksummed address

---

audit-ci.jsonc
src/core/resources/nfts/collections.ts
src/core/resources/nfts/nftsForCollection.ts
src/entries/popup/hooks/send/useSendUniqueAsset.ts
src/entries/popup/pages/home/NFTs/NFTCollectionSection.tsx

Fixes BX-1702
I am mocking NFT data in our test flows to ensure reliable responses.
Note: I am including this [change](https://github.com/rainbow-me/browser-extension/pull/1766) for expediency.
Checkmark on CI will be PoW.
Determine if this change can produce any false positives in our testing flow.

Mock NFT Send Flow Data

---

src/core/raps/actions/swap.test.ts
src/core/raps/actions/swap.ts
src/core/raps/execute.ts
src/core/raps/unlockAndCrosschainSwap.ts
src/core/raps/unlockAndSwap.ts
src/core/raps/utils.ts

Please see details on corresponding PR: https://github.com/rainbow-me/rainbow/pull/6259
Separate error on BX:
A change caused the `permit` flag to be sent for all ERC20s on all networks even if the ERC20 did not support permit.
Introduced in: https://github.com/rainbow-me/browser-extension/pull/1746/files#diff-2f8283f2d99b48500b1dba49e5fdf8a9e34914021392d58d25878323dd82d149R115

Remove permit support and modify node ack logic

---

src/core/raps/execute.ts

* Surrounded the `waitForNodeAck` logic in try catch and follow the same retry pattern up to 10 max retries
Brody had confirmed PoW on Zora.

Match waitForNodeAck logic to be same as in app

---

package.json
yarn.lock

Resolves https://github.com/advisories/GHSA-3xgq-45jj-v275
Good to go if CI is green

chore: pin cross-spawn to 6.0.6

---

README.md

Update Edge browser logo URL
Changed the Edge browser logo source from Wikimedia to jsDelivr CDN for better reliability and performance.The previous icon was not displayed correctly
Before:
After:

Replace broken Edge browser logo with working version from jsDelivr CDN

---

.github/workflows/publish-internal.yml
.github/workflows/publish-prod-chrome.yml
.github/workflows/publish-prod-firefox.yml

Just removing that, which I don't think we need and it expired so it's blocking release

Femove unncessary token from publish jobs

---

package.json
static/manifest.json

Doing a manual bump because https://github.com/rainbow-me/browser-extension/actions/runs/12305640395 went through but failed to commit bc of an expired token.
We need this otherwise versions will collide and we'll be rejected

Version Bump (Internal) - v1.5.65

---

src/entries/popup/pages/messages/useSimulateTransaction.tsx

Fixes BX-1733
* This is a non-urgent PR but good to have for future networks we want to support that might not have transaction simulation support. In this scenario, the simulation response does not return the data that we expect, and we were trying to index into nonexistent simulation data. Updated for both transaction and message simulation paths. 
* You won't be able to test this out as of now, as we've turned on transaction simulation support for Ink, so you'll only see the success state. Locally, I tested with a "fake" bad response that was the same as what we were previously getting before Ink support was turned on.
Screen recordings for the resolved state can be seen on the associated Linear ticket.

Handle error states for when txn simulation is not yet supported for a network

---

src/analytics/event.ts
src/entries/popup/components/ImportWallet/ImportWalletViaPrivateKey.tsx
src/entries/popup/pages/hw/ledger.tsx
src/entries/popup/pages/hw/trezor.tsx
src/entries/popup/pages/walletSwitcher/addWallet.tsx
src/entries/popup/pages/walletSwitcher/chooseWalletGroup.tsx
src/entries/popup/pages/walletSwitcher/newWatchWallet.tsx

Fixes BX-701
added a `wallet.added` analytics event, triggered every time the user successfully create/imports/connect or watch a new wallet 
the event metadata is 
```ts
type: 'HdKeychain' | 'KeyPairKeychain' | 'ReadOnlyKeychain' | 'HardwareWalletKeychain'
vendor: 'Ledger' | 'Trezor' // only included when the type is 'HardwareWalletKeychain'
isNewGroup: boolean // only included when the type is 'HdKeychain'
```

create wallet analytics

---

src/entries/popup/components/CommandK/useCommands.tsx
src/entries/popup/hooks/useDeviceUUID.ts
src/entries/popup/pages/settings/settings.tsx
static/json/languages/en_US.json

Fixes BX-1717
Goal as explained in the ticket:
- Add diagnostic Cmd K actions when when searching Diagnostics (should be hidden otherwise)
- Create a Copy UUID action that copies the deviceId to the clipboard with a toast
- When clicking the version number at the bottom of the Settings, trigger the same Copy UUID action
- Added a hook for handling user UUID and the copying action / toast
- Added the commandK action searchable by 'Diagnostics' as described in ticket. if 'Diagnostics' in it's entirety isn't searched for, the command will not surface
- Also added the ability to copy the UUID to clipboard by double-clicking the version number on the settings sheet
<video src="https://github.com/user-attachments/assets/9edfa6ea-7837-4e01-8257-7e59f50b8af6" />
- is the command hidden until …

Surface UUID in a more user friendly way for support

---

src/core/storage/localStorageRecycler.ts
src/entries/background/index.ts

During performance investigations, we discovered that old installations of the browser extension are carrying unnecessary storage weight from deprecated WAGMI data (8-11MB) that was left behind after our migration to Wagmi v2 in May. This legacy data primarily consists of RPC logs and token metadata that is no longer accessed or needed.
While recent installations don't have this overhead, older installations are experiencing slower boot times, potentially exacerbated by Chrome 131's handling of chrome.storage.local bootstrapping. The combination of:
- Deprecated `rainbow.wagmi` storage (8-11MB)
- Active `rainbow.react-query` storage (2-4MB)
Is likely contributing to startup performance issues.
I've implemented a `localStorageRecycler` utility that:
- Runs during extension initialization …

Clear deprecated WAGMI storage via `localStorageRecycler` to improve extension boot performance

---

e2e/helpers.ts
e2e/parallel/importWalletFlow.test.ts
e2e/walletVariables.ts
src/entries/popup/components/ImportWallet/ImportWalletViaSeed.tsx

Fixes BX-1623
- adds a test to check 24 word seed phrases
- refactors seed import helper to work with 24 word phrases
- adds 24 word secret and address to the variables file

24 word secret phrase e2e validation

---

e2e/helpers.ts

Chrome wasn't starting properly in CI last week. Added a couple flags to our chrome args seemed to fix it.
Added `--no-sandbox` and `--disable-dev-shm-usage` flags to Chrome test initialization to fix the "session not created" errors in CI. These flags are required for Chrome to run properly in containerized CI environments where the default sandbox permissions and shared memory settings are insufficient.
More about the flags:
- `--no-sandbox`: Disables Chrome's sandbox security feature which often can't get the necessary permissions in CI containers
- `--disable-dev-shm-usage`: Forces Chrome to use /tmp instead of /dev/shm for shared memory, preventing crashes from insufficient memory allocation in CI containers
- `--disable-extensions-except=build/`: Only leaves our extension enabled. …

Add Chrome flags to fix CI test startup

---

e2e/serial/swap/1_swapFlow1.test.ts
package.json

Updates the anvil command configuration to provide more stable and predictable gas behavior during local testing.
Changes:
- Added `--block-base-fee-per-gas 5000000000` (5 gwei) to set a consistently low base fee.
- Added `--block-gas-limit 30000000` to fully mock the gas params we can control.
- Changed how we clear the input. Saw some flakiness around that as well.
This change addresses transaction failures related to gas price fluctuations in our test environment and provides a more reliable setup for local development and testing.

[fix] configure anvil with consistent gas parameters

---

src/core/graphql/__generated__/metadata.ts
src/core/resources/networks/queries.js
src/core/state/networks/networks.ts
src/entries/popup/pages/swap/index.tsx

fixes BX-1643
We modified our graphql query to include the exact output flags from backend, ran the networks script, and created a new flag the disable to buy input whenever instructed.
[BX-1643 PoW](https://www.loom.com/share/5fdb2de1417a408a85a73fbea534d264)
Ensure the buy input behavior mirrors the app.

fix: respect backend network exact output flags

---

package.json

added `yarn tag-version`
dev QoL, adds script to push a tag corresponding to current version

add tag-version script

---

src/design-system/styles/designTokens.ts

Fixes BX-1786
- 'ink' was missing from the `textColors` array in our `design/Tokens` causing a crash when a user went to bridge to ink chain.
- checked all our other rainbow chains manually and didnt see the issue anywhere else.
Before:
<video src="https://github.com/user-attachments/assets/6b297806-01d0-4942-8fe1-d8e22fc686fb" ></video>
After:
<video src="https://github.com/user-attachments/assets/554dc2da-0f82-47ec-8b63-9ed6c6d6b5d2" ></video>

crash fix when bridging to Ink

---

src/entries/popup/pages/messages/SignMessage/SignMessageInfo.tsx
src/entries/popup/pages/swap/SwapReviewSheet/SwapAssetCard.tsx
src/entries/popup/pages/swap/SwapReviewSheet/SwapReviewSheet.tsx

Fixes bx-1748, bx-1762
Overflow issues with emoji tokens in review sheet:
- added text overflow where necessary
- limited max width of some components.
Before:
After:
x-overflow issues on message signing requests with long unbroken hashes:
- made the y-overflow scrollable
- formatted the json properly
- word-break applied as expected
Before:
(incredibly long x-overflow scrolling)
After:

[bx-1748] [bx-1762] Fixes a couple of overflow issues

---

src/core/messengers/initializeMessenger.ts
src/core/messengers/internal/bridge.ts
src/core/messengers/internal/createMessenger.ts
src/core/messengers/internal/extension.ts
src/core/messengers/internal/tab.ts
src/core/messengers/internal/window.ts
src/core/storage/index.ts
src/entries/background/handlers/handleOpenExtensionShortcut.ts

Adds reconnection logic to messengers so that we can restore connection when BFCache is triggered. I also added some logic to remove potential for duplicate listeners inside of messengers.
n/a
make sure messengers don't experience dropped data / can reconnect on BFCache

Fixes broken messenger connection due to BFCache

---

src/core/resources/nfts/collections.ts
src/core/resources/nfts/galleryNfts.ts
src/core/resources/nfts/nftsForCollection.ts
src/core/resources/nfts/useNft.ts

I bumped the nft cache to hold data indefinitely in preparation for Simplehash going down.
Ensure NFTs still appear, evaluate whether these changes may have any unintended consequences that I may have missed

chore: set indefinite nft cache time [BX-1789]

---

src/core/utils/signMessages.tsx

Fixes BX-1776 (CAAAW!!!! 🦅🇺🇸🎆)
Fixes an issue where hex-encoded messages in personal_sign requests were being incorrectly identified as Ethereum addresses, causing the message and address parameters to be swapped. This resulted in unreadable text being displayed to users.
Before:
After:

fix message decoding

---

CHANGELOG.md

- Fixed crash when bridging to Ink network #1878
- Fixed multiple overflow issues #1879
- Resolved broken messenger connection due to BFCache #1877
- Fixed issue with message decoding #1880
- Added analytics events for token favorites and hiding #1845
- Implemented additional security fix from audit #1884
- Set indefinite NFT cache time for improved performance #1883
- Added tag-version script for improved version management #1866
- Updated to use Target from Swap SDK for enhanced swap functionality #1859
- Fixed useUserChains filtration to properly account for mainnetId when disabling certain features #5a667e1
- Replaced `withSelectors` usage with hook derived from createRainbowStore for better state management #c712821
- Implemented security fixes from recent audit #1874
- Upgraded BPP …

changelog for last 2 releases + prettier the file

---

CHANGELOG.md
src/entries/popup/pages/messages/SendTransaction/SendTransactionsInfo.tsx

Users who only own non-native tokens on a chain (like wDEGEN but no DEGEN) weren't seeing gas warnings when attempting to sign txns only a blank sign transaction screen with a cancel button. This occurred because our UI relied solely on useUserNativeAsset which returns undefined when the native token isn't in the wallet.
- Added useNativeAsset hook to the InsuficientGasFunds component to always fetch the chain's native asset metadata
- Kept useUserNativeAsset for checking user balances
- Modified UI logic to use chain metadata for display purposes while still checking user balances for conditional messages
Updated button action handlers to use the appropriate asset reference
| Before | After |
|--------|-------|
| <img width="280" alt="UI Before" …

Insufficient gas warning not displayed when no nativeAsset

---

.github/workflows/publish-internal.yml
.github/workflows/publish-prod-chrome.yml
.github/workflows/publish-prod-edge.yml
.github/workflows/publish-prod-firefox.yml
lavamoat/build-webpack/policy.json
package.json
static/manifest.json

Fixes BX-####
- removed default github action workflow tokens to prevent failed action commits for expired tokens

fix: deprecate non-default workflow token

---

src/entries/popup/pages/home/TokenDetails/PriceChart.tsx

Fixes BX-1833
The underlying issue is not fixed, but also not reproducable and it looks like it was temporary. My guess is due to missing data or malformed data from backend.
This PR makes sure only the chart crashes next time, and the rest stays functional
https://github.com/user-attachments/assets/11c7b458-22c2-49e6-8d4e-f07147f25519

fix: handle chart errors

---

package.json
yarn.lock

Fixes BX-####
- upgraded wagmi to `2.16.1` and viem to `2.31.7` (these are pinned to match wagmi codebase)
- added and pinned ox at `0.8.7`; this is ahead viem's `0.6.9` usage
- Network operations (should leverage wagmi/viem)

chore: upgrade and pin wagmi, viem, ox

---

src/core/state/index.ts
src/core/state/requests/index.ts
src/entries/background/procedures/popup/state/requests.ts
src/entries/popup/ProtectedRoute.tsx
src/entries/popup/pages/home/index.tsx
src/entries/popup/pages/messages/ApproveAppRequest.tsx
src/entries/popup/pages/welcome/index.tsx

- Modified `usePendingRequestStore` to be accessible from both background and popup contexts
- Moved the `onlyBackground` check from the store initialization to individual methods that should only be called from the background
- Exported the store from the main state index for easier imports
- Updated all popup components to directly use the store instead of querying the background via RPC
- Removed the now-unnecessary `getAll` handler from the requests router
- Verify that pending requests still appear correctly in the popup
- Confirm that approving and rejecting requests still works properly
- Check that the background-only methods throw appropriate errors when called from the popup
- Ensure that the home screen, protected routes, and welcome page still display pending requests …

fix: delay in signing

---

src/core/sentry/index.ts
src/entries/background/procedures/popup/index.ts
src/entries/background/procedures/popup/wallet/wallet.ts

- Exported `INTERNAL_BUILD` and `IS_TESTING` constants from the Sentry module to make them accessible in other parts of the application
- Added Sentry breadcrumbs for ORPC calls in the `sentryMiddleware` to improve debugging capabilities in internal builds and testing environments
- Added Sentry breadcrumbs for wallet address access to track wallet-related operations during development and testing
- Verify that Sentry breadcrumbs are properly added for ORPC calls in internal builds and testing environments
- Confirm that wallet address operations are correctly tracked with breadcrumbs
- Ensure that breadcrumbs are only added when `INTERNAL_BUILD` or `IS_TESTING` is true
- Check that the existing error handling in the Sentry middleware still works as expected

feat: add more breadcrumbs to internal builds
